### ISSUE TITLE
Don't add specials to library

### ISSUE THREAD

**Issue by torbvea** [scakemyer/plugin.video.quasar#104]
Just wonder if it's possible to choose not to add special episodes when adding a TVShow to the library? 

I also noticed that some TVShows contains episodes that's not released yet. Is it possible to only add episodes which is released and then the library will automatically update when there is a new release.

**Comment by i96751414** [comment]
About the specials, yes, it is possible to implement that.

About the not released episodes: Can you provide an example?

**Comment by torbvea** [comment]
Thanks for the quick response.

Some examples are: Arrow, The Flash and The Blacklist. Episode 16 or 17 is added to the library before it's released.

**Comment by Magic815** [comment]
Just to add my thoughts, I think It would be good to have a user setting define if they want special episodes added. Maybe default it to off? And then would it make sense to have a "Ignore Not Aired Episodes" setting as well? I'm trying to think if there might a group of people who want to have it show up, even if it's not quite available yet.

**Comment by i96751414** [comment]
Fixed ;) About the specials, I don't think it's a good idea to have an option to enable/disable specials. It should be enabled/disabled by default. Let's see what @scakemyer thinks about this.

**Comment by Magic815** [comment]
Can you elaborate on why? Personally, I wouldn't want to see specials in my TV episode lists. But that's just me. I imagine that there are other people out there that would prefer to have specials shown, though. Why not make it a user selectable setting? I guess I'm confused.

**Comment by i96751414** [comment]
I like your ideas, the problem is that it brings some complications. Imagine you enable it, then add one show to Library and then you disable it. The specials files will stay there... They will not appear only on future shows

But well... I'll take a look at this later and change the way that Update function works (first delete old entries and then add again).

**Comment by Magic815** [comment]
Gotcha. I'll admit I was just thinking from a usability standpoint from the user, and not the complexity of the coding/system behind it. If it ends up being too much of a headache to implement a setting, my vote would be to have specials not included.

But your comment on the update function is getting me thinking. What if Quasar had a global 'update/refresh' setting that could be run? So that if I changed some sort of setting in Quasar (like suddenly wanting specials), it would add them to all existing shows. I think a system like that would be key anyways for Trakt integration (https://github.com/scakemyer/plugin.video.quasar/issues/31) and duplication handling (https://github.com/scakemyer/plugin.video.quasar/issues/32) anyways, right? Should I make another issue request for that discussion?

**Comment by i96751414** [comment]
Umm, that's a good idea. Maybe a 'RebuildLibrary' function can solve this problem... Doing this later

**Comment by scakemyer** [comment]
A rebuild function would be great, and could be called automatically when settings are changed, just like the libtorrent reload of settings, while also allowing the user to trigger the action manually. Since it'd be an expensive thing, it wouldn't be called on library updates, and should probably show a background progress dialog.

**Comment by hfmls** [comment]
Specials off (my opinion) would be great :)

**Comment by scakemyer** [comment]
This should probably be a setting.

**Comment by nix87** [comment]
another vote for special off :)

they are also very hard to get on torrents anyway if someone even want to have them and if after all you find some there is very few seeders for those episodes and stream would be very hard

**Comment by m4xc4v413r4** [comment]
Yeah, i vote special off too :)

**Comment by drake0101** [comment]
+1 don't add specials to library ;)

**Comment by BTopbas** [comment]
+1 for specials off. Not need to specials. But also user settings is fine.
