### ISSUE TITLE
Add library integration

### ISSUE THREAD

**Issue by scakemyer** [scakemyer/plugin.video.quasar#11]
@i96751414 Did that require changes to daemon also? Otherwise I could just cherry-pick your previous commit.

**Comment by hfmls** [comment]
Add trakt scrobble too pls

**Comment by i96751414** [comment]
Yes, it requires a lot of changes. But don't worry, i got this

**Comment by Magic815** [comment]
Just to expand on this, I'd love to see the integration include Trakt lists (meaning the default Watchlist and custom lists). One of Mancuniancol's scripts had the ability to only sync with Trakt lists that contained the keyword 'Pulsar'. That was a great feature, since it allowed me to separate movies/shows that I wanted integrated into Kodi, and ones that I didn't want integrated.

Other than that, integration with IMDB watchlists would be great too.

**Comment by scakemyer** [comment]
@Magic815 Please open a separate issue for Trakt, same for IMDB watchlists and duplicates handling. Makes it easier to keep track of things :)

**Comment by scakemyer** [comment]
@i96751414 Add "fixes #x" in your commit message when you know it closes a certain issue, so GitHub closes it when it gets merged :)
