### ISSUE TITLE
Ask to keep the file

### ISSUE THREAD

**Issue by Wailerman** [scakemyer/plugin.video.quasar#14]
Pls add an option to ask to save the file you are going to download just after choosing the stream source when keep filles after playing is disabled in Quasar config.
I dont want to keep the files except for those my children wants to see all the time !!! :)
BTW, tks so much for your excellent work !!!

**Comment by Magic815** [comment]
To piggy back on this idea, here are my thoughts on how to best handle this:

Have a setting inside Quasar that has three options. Lets tentatively call the setting "Desired Action Upon Completion." The three options would be Delete, Keep, and Ask.

If Delete is selected, then all streams will automatically delete after the stream has completed. If Keep is selected, then the file stays in the designated download folder. If Ask is selected, then every stream will have a dialog box appear at it's completion asking the user if they would like to delete or keep the file.

To take it one step further, I'd recommend having a separate setting for Movies and TV shows, so that users can have complete control over how they want their streams handled upon completion. (For example, I could have TV Shows set to 'Keep', but Movies set to 'Ask', if that's the desired handling I'm looking for).

Thoughts?

**Comment by Wailerman** [comment]
@Magic815 I like your idea !!

**Comment by drake0101** [comment]
Maybe a simple radio switch (Keep file ON/OFF) on the bottom of the  "Choose stream" window?

**Comment by scakemyer** [comment]
That's also a very good idea.

**Comment by Magic815** [comment]
Isn't there a setting that allows for Quasar to auto-select the highest ranked stream? (Effectively circumventing the 'Choose Stream' window). If that's the case, there would be no radio switch visible for those who use it that way.

Also, that would effectively be asking the user to make the decision before they watch the stream. In the case of movies, it might not be until the end of the movie that a user may decide if it's worth keeping or not. I kinda like the idea of allowing the user to decide at the end (which would go with my 'keep/delete/ask' idea above).

**Comment by palula** [comment]
I think that feature is already present in Quasar, @Magic815. At least mine shows a radio button for me to turn on/off in case I like to choose my sources manually (which in turn is my preferred setup).

By the way, I'm using Quasar [v0.9.25](https://github.com/scakemyer/plugin.video.quasar/releases/tag/v0.9.25) for the [Raspberry PI 2](https://www.raspberrypi.org/products/raspberry-pi-2-model-b/).
