### ISSUE TITLE
Delete Torrent once streaming another movie

### ISSUE THREAD

**Issue by cyberjoac** [scakemyer/plugin.video.quasar#182]
Hi,

I have very limited space on my Android Box device, and I was wondering if there was an option in order to delete the currently streaming torrent, once I decided watching another movie (and hence started streaming it though libtorrent).

I tried playing with the parameters in the extension but without success.
Any help would be much appreciated, thanks!

**Comment by gpiano** [comment]
Any news about it? Maybe a workaround to do this? Thanks!

**Comment by hfmls** [comment]
yes, delete after watch isn't working

**Comment by gpiano** [comment]
If you are a developer (and have knowledge of the source), seems that deleting the torrent data when you hit Stop button isn't a big problem to fix... any ideas how to do it? Thanks!

**Comment by scakemyer** [comment]
Delete after watch is working fine with background handling disabled. When it's enabled you're currently expected to delete it from the Torrents menu, which deletes according to your Keep files after download setting. Auto-deleting those will be fixed in #147. There's currently an issue I haven't filed about a race condition, where fast resume data gets flushed right after deleting a torrent, which causes the torrent to re-appear on the next start, but that's unrelated.

@gpiano When you're not a developer, it's easy to say "when you're a developer".

**Comment by gpiano** [comment]
Thanks for your quickly answer. My statement wasn't meant to be derogatory, I'm also a developer... unfortunately I don't have the time to see the source. Thanks again!
