### ISSUE TITLE
Start playing file at specified buffer  %

### ISSUE THREAD

**Issue by exzilexv** [scakemyer/plugin.video.quasar#223]
This is mostly for under powered machines (Raspberry Pi) but would also benefit all others as well.  As it stands now you can set buffering by MB's, but with the influx of different file sizes it would be much better to start at a specified %. Since most of the time you would have to pause the video for it to buffer until you feel the amount downloaded is safe enough to continue without it stopping while viewing. Like me personally wont start a video until its been at least 50% downloaded, but that's just me. Thanks for considering this, the less clicks the better. :)

**Comment by m4xc4v413r4** [comment]
Actually, a fixed size is always better than a %.

Connection speed isn't a %, nor is bitrate.
If a movie has a 8 Mb bitrate that means you need at least 8 Mb of constant connection to watch it without buffering. If you give it a 20 MB buffer you just gave it 20 sec of video that it can use if the connection drops below the minimum 8Mb.

A % won't work well, if you give a low percentage it might be enough for a low bitrate video but not really for a high bitrate video, if you give it a high % it will be OK for a small file but on a huge file you'll be buffering it forever because it'll be a huge buffer size.

**Comment by lcaleixo** [comment]
@exzilexv What is the skin that you are using with kodi? :) issue #171

**Comment by scakemyer** [comment]
Agreed, I also thought about this and let's say you'd put it at 50% because you have a slow connection, and it takes 1 hour to reach that 50%. Chances are you won't be waiting for it to start, and when it does you'll be doing something and might not even be around. Fixed buffer size is the way to go, just use background handling or just set the fixed size higher.
