### ISSUE TITLE
Movies List Crash

### ISSUE THREAD

**Issue by morcegon** [scakemyer/plugin.video.quasar#226]
Hello!

I'm having a crash when I choose any item on Movie menu.
This is the link for log: http://pastebin.com/jUw9g4f7

Thanks

**Comment by Clavisnl** [comment]
Same here...

**Comment by jbarren** [comment]
Yeah me too. Looks like the latest update from 0.917 to 0.9.18 caused it.

**Comment by scakemyer** [comment]
It wasn't the update, the MovieDB API key got suspended:
```
{"status_code":10,"status_message":"Suspended API key: Access to your account has been suspended, contact TMDb."}
```

**Comment by Clavisnl** [comment]
Any idea why? And how to fix it. Quasar is crashing whenever i try to start a movie or serie. Thanks in advance.

**Comment by scakemyer** [comment]
I'm not sure if this is even related to Quasar, as the API key that was being used seemed to be shared by other add-ons also, but I do suspect we might have caused its revocation. I've got a hotfix on the way, since I really don't feel like rewriting half the daemon to use a different service. It does raise a flag about the need to have swappable back-ends for movie and tv shows listings, so we'll be heading that way in the medium-long term.

**Comment by i96751414** [comment]
This might be a dumb question... But why not get a new key? You should also change all the other keys to keys requested by yourself.

**Comment by scakemyer** [comment]
Feel free to go request one yourself and give your real street address, since they review all requests and demand to have real informations. I'm just not taking that risk, already made an account but had to back down when I saw their requirements for a new API key. Any kind soul willing to get an API key in the name of Quasar would be greatly appreciated, but I'm not going to.

**Comment by bluenote73** [comment]
I'm not crazy about doing it, but I'm willing to have a conversation with them about it at least, is this a must-do or just a nice-to-have?

**Comment by KillerJoeBR** [comment]
Could be a solution to have the quasar users register at TMDB website and then enter our personal key into the quasar settings? Probably not the best solution but if it's easy to get a pesonal key i wouldn't mind. (something like a trakt account).

**Comment by scakemyer** [comment]
It's a must-do or must-workaround indeed. You've got my support if you go ahead with this, you're a lot more diplomatic than I am, more chances to get somewhere :)

@KillerJoeBR I checked, they don't make it easy to get an API key. I'll probably add the setting anyway, which won't hurt for those that can get one and use that.

**Comment by i96751414** [comment]
@scakemyer I already have one key that I've requested a long time ago... And I can guarantee that I did not introduce any personal details.

**Comment by KillerJoeBR** [comment]
I think i got one key now. It was automatic and quite easy. You do need to fill a request but i dont know if you need to enter valid information.

**Comment by bluenote73** [comment]
PM'd you mine on kodi forum @scakemeyer.  I couldn't figure out how to send a PM on here.

**Comment by scakemyer** [comment]
Alright, got one also, but they could revoke it at any time considering the fine line we're walking, and from the simple fact that we're openly not filling requests with real information.

**Comment by nix87** [comment]
I hope they don't read this thread... hehehe xDD

Anyway I will also try to register and get API key and for just in case I will make some donation sometimes in next copule of weeks or month :D I would like to see to get banned after I make donation.. hahaha

**Comment by endlessterror** [comment]
This might explain why I was having a ton of problems yesterday, under .18. Apart from search, nothing worked. Additionally, instead of the multitude of categories (action, drama, horror) presented under either movies or tv, now only less than 6 options were presented and none of them worked... 

One question though: if one does enter a TMDB API key, what kind of functionality "crippling" can he expect? No categories, new releases etc?

**Comment by scakemyer** [comment]
This will all be fixed in the v0.9.19 release coming up in a few minutes.

If you do add your own API key, the functionality will be the same and unless your own key gets revoked, you will not depend on the default key in Quasar.

**Comment by bluenote73** [comment]
Props scakemeyer that's awesome turnaround time. Thanks!

**Comment by scakemyer** [comment]
Thanks, but I found I was pretty slow on this one. I was in the process of refactoring the seasons and episodes so they'd use TMDB instead of TVDB and was almost done when this happened. I also wanted to do it right, to add the setting for a custom key, a check for the current key, automatic rotation on failures, and better error handling of all the calls (there was none...) So it took quite longer that I would've wanted, but I think the result is worth it. And there's the multi-cloud icon too ;)

**Comment by scakemyer** [comment]
And v0.9.19 is up, closing this darn issue and hoping we won't have to deal with this on a regular basis.
