### ISSUE TITLE
Network interface choice

### ISSUE THREAD

**Issue by dtony** [scakemyer/plugin.video.quasar#295]
It would be great to be able to chose the network interface used by Quasar, at least for the torrent downloading. Then it would be possible to force VPN usage (tun0 for instance). Additionally there could be an option to "do not start bittorrent download if custom interface is not available" or the opposite : "start bittorrent download on other interfaces if custom interface not available" (the second on would be preferable and unchecked by default IMHO).

I found that libtorrent support it via the listen_on function for which we can pass a "char const\* interface".

**Comment by bluenote73** [comment]
I love this idea.  Then there's no need to worry about fancy and failure-prone killswitches etc.

**Comment by Rick7C2** [comment]
I would also like to see this feature.

**Comment by scakemyer** [comment]
Seems like an easy thing to add, and a better approach than relying on proxy settings left and right, but we're not going to start checking if network interfaces are available or not. Still, I don't get why folks keep hammering that nail instead of using a dedicated device... which is also where such interface switching should be done, and not on the same device as your media center.

**Comment by Rick7C2** [comment]
@scakemyer What would be the best way to do this then? I've tried setting a vpn up on my dd-wrt router with iptable kill switch but the network speeds are so slow it defeats the purpose. Once we get some private tracker providers for quasar like PTN(Movies Ratioless), BTN(TV Ratioless), and PTP(Movies Ratio) this will not be an issue. The only problem I see is with BTN because once the full tv season has been released they delete all single episode torrents except the pilot.

**Comment by incredulity** [comment]
> hammering that nail instead of using a dedicated device

For $500 Alex, What is money?

**Comment by BinaryNumber** [comment]
Hello,

I'm trying to use this feature from Kodi on OSMC.
I'm wondering how to filling "Listen interfaces" and "Outgoing interfaces" options?
I'm trying with interface name "tun0" but it seems not working (torrent downloading isn't starting)
