### ISSUE TITLE
Trakt List Integration

### ISSUE THREAD

**Issue by Magic815** [scakemyer/plugin.video.quasar#31]
It would be great to see Quasar have the built-in ability to take movies and TV shows that users have on their Trakt watchlist and various custom lists, and integrate them into the Movie/TV show libraries within Kodi.

Specifically, it would be nice to break out the integration by having the following settings (or something similar):

"Integrate Trakt Watchlist" -- Off/On
"Integrate Trakt Custom Lists" -- Off/On
........"Only integrate custom lists with the below keyword" -- Off/On
..................."Keyword" -- Quasar (Or could be modified to anything else by the user) 

Mancuniancol's Trakt Subscription List that worked with Pulsar pretty much did exactly the above. Maybe it would be good to check out that addon's code?

**Comment by hfmls** [comment]
it has been said it's gonna be integrated into Quasar, also scroblle :) can't wait to retire GENESIS.

**Comment by hfmls** [comment]
i see there is an option of adding tv shows to local library, is there trakt tv collection list integration also?

**Comment by emerleite** [comment]
I tried Trakt list subscription plugin and worked fine.

**Comment by Magic815** [comment]
Just to further discuss this idea, it might be good to have the implementation of this include settings that allow for an automatic scan of new shows in the Trakt lists at startup. Again, please reference @mancuniancol's Trakt subscription plugin that was made for Pulsar. It effectively consisted of a check box setting for if users wanted a scan at startup. But then it also allowed for a user-selectable time delay, as running it immediately could cause problems.

**Comment by likeitneverwentaway** [comment]
It would be great to have the option to choose a directory for each list subscription, so it would be easier to have our Trakt list in Kodi playlist based on the path name.

**Comment by scakemyer** [comment]
I started working on Trakt integration, so far only getting Trending/Popular/etc lists for movies (most of the work is just about updating to the new API and data structures). Just that reduces our dependence on TMDB so it's a great start. TV Shows will take a little longer since it's a pain just to get the structs right and loading data, but it'll catch up.

I suppose once that's done it shouldn't be too much trouble to integrate custom lists. I don't want to duplicate the work done by MC but it might be more convenient to have those right in Quasar.

Scrobbling will take more work also, as it requires the implementation of PIN authentication, but once that's done, it might actually be more straightforward than marking .strm files as watched in Kodi...

**Comment by mancuniancol** [comment]
@scakemyer, if you need help with that. Let me know.

**Comment by hfmls** [comment]
if possible please also add option to import "collection" list please.
thank you very much.

**Comment by m4xc4v413r4** [comment]
Didn't he say he was already working on it? Let's let the man work, I don't see a lot of people rushing to help so let's give him some breathing room, it's not like he owes us anything.

**Comment by hfmls** [comment]
is scrobble supported too? thank you.
