### ISSUE TITLE
Quasar crashes with update to 0.9.24 on Raspberry Pi 2 and 3

### ISSUE THREAD

**Issue by Penningmeester** [scakemyer/plugin.video.quasar#331]
When quasar is updated to 0.9.24 pulsar is unable to find its binary's on RP2. it is not the same issue as #160 because the update is downloaded directly from the quasar release page here on github and not from a third party repo. Issue is resolved when downgrading to 0.9.23.

**Comment by deusbraga** [comment]
I've downloaded from the official github page and I have the same mistake on a RPI3, not just that but if I try to use the biggest file to install I receive an error message forcing me to install the linux arm or linux arm 64 versions after which it shows the message unable to find binary

**Comment by luukholleman** [comment]
Can confirm, same issue with updating on rpi 3. Downloaded from the releases page

**Comment by m4xc4v413r4** [comment]
mmh, maybe something got broken with 

> Added support for linux-armv7 and linux-arm64, #26

**Comment by scakemyer** [comment]
Guys, I'll be happy to fix this with another release asap, but how many times do we have to ask for logs to be able to help?

**Comment by deusbraga** [comment]
wll send the log as soon as I get home and figure out how to extract the log out of the rpi3

**Comment by scakemyer** [comment]
Thanks, and specially for testing on rpi3 (lucky bastard).

**Comment by m4xc4v413r4** [comment]
To get the log out you can simply install a log upload addon, or ssh in from your computer or even phone/tablet, it's really easy.

**Comment by lordjg** [comment]
fixed after update to armv7

**Comment by m4xc4v413r4** [comment]
Apparently everyone with a pi that i know is having this problem, i already asked them for a log.
If they send it i'll post them here.
Downgrading to .23 "fixes" the problem confirmed.

**Comment by scakemyer** [comment]
Yeah a downgrade is never a fix, but idiots don't understand that. Been waiting all day for some logs so I can push a release to properly fix it.

**Comment by MrLegendary** [comment]
[Here](http://goo.gl/AcfKjA)'s my log

**Comment by m4xc4v413r4** [comment]
mmh, you log seems very incomplete... did you get the error from quasar during that time?

Anyway, [v.23 for comparisson](http://xbmclogs.com/pajk5ondx) and [v.24](http://xbmclogs.com/prod7gt4r)

**Comment by MrLegendary** [comment]
Couldnt find much in there either. But I did get the error.

**Comment by seltun** [comment]
Starting at reboot after installation of version 0.9.24
[xbmclogs.com](http://xbmclogs.com/pn5upzk98)

**Comment by JoaoEdu93** [comment]
I also have this problem on Windows 10.
[Here](http://xbmclogs.com/pxdtd8zui)'s my log.

**Comment by scakemyer** [comment]
If any of you can try with that commit before I push a release that'd be great (except you Windows dude, this is a raspberry/arm issue)

**Comment by NerosTie** [comment]
@scakemyer It works with that commit.

**Comment by scakemyer** [comment]
Yeah... but folks are reporting it's also working with linux_armv7, so it's actually the upgrade process... v0.9.23 still only recognizes linux_arm, downloads that update, which then tries to use linux_armv7 that can't be found. So that fix is not really a good one since it prevents those on rpi2 and 3 to use the binaries that are more optimized for their architecture.

**Comment by scakemyer** [comment]
So I need the uname from a rpi3, and someone with one of those to check with the linux_arm64 release if that works on those. If so then it's just a matter of manually updating for this one, as there's no easy way to make that upgrade.

**Comment by scakemyer** [comment]
From @deusbraga's comment and what I can find about rpi3, linux_arm64 won't work on it, which is what it was trying to use in 0.9.24 from a clean install, and linux_armv7 probably would but wasn't getting selected (trying the all-binaries release or linux_armv7 wouldn't work either, again because it would go for linux_arm64). I'll adjust the previous fix for that, and mention the upgrade process for those on rpi2/3 in the release notes.

**Comment by kostaboxon** [comment]
MXQ S805 Running linux 6.0.1.4 i had the issue with unable to find binary.
I installed plugin.video.quasar-0.9.25.linux_armv7.zip.
FIXED MY PROBLEM. Working again. Thank you.

**Comment by deusbraga** [comment]
This is the log of what happens when I try to install the general version
of 9.24 and then the arm 64 bits on RPi3:
http://xbmclogs.com/pgz8orkku
This log refers to the attempt to install quasar 9.24 arm on a RPi3
http://xbmclogs.com/p70vt9y6q

Sorry for taking so long to post them but Wednesdays and Thursdays are busy
days for me. Thank you for paying attention to my problem.

Offtopic: is there anything u can do to make sure the 3rd party subtitle
addons receive the original title of the files? Apart from quasar the
others I've tried keep giving me all sorts of stupid results.

Thank you again

2016-03-03 2:27 GMT+00:00 scakemyer <notifications@github.com>:

> If any of you can try with that commit before I push a release that'd be
> great (except you Windows dude, this is a raspberry/arm issue)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scakemyer/plugin.video.quasar/issues/331#issuecomment-191547336>
> .
>



-- 
Great men are forged in fire. It is the privilege of lesser men to light
the flame. Whatever the cost. Warrior Doctor

**Comment by scakemyer** [comment]
Please try 0.9.25 with the linux_armv7 on rpi3, linux_arm is just for rpi1 now.

**Comment by luukholleman** [comment]
It works, thanks :)
