### ISSUE TITLE
private trackers

### ISSUE THREAD

**Issue by sonics007** [scakemyer/plugin.video.quasar#358]
so now is it possible to use any private trackers?

**Comment by nix87** [comment]
Well I don't know how this should go and who needs to take this Quasar or providers but I tried several privite trackers and they don't work with simply copying torrent file in Quasar torrent URL. He can't play torrent like that. The only private tracker which i tested and he make it to work is UHDBits. That tracker is fully privite and solid one too anf for some reason he want to work on Quasar unlike others which I have tested.

**Comment by scakemyer** [comment]
You can't paste torrent file URLs, that's only for magnet URLs. You need to download the torrent file and use the File option in the Add Torrent menu, or convert the torrent file to a magnet link and use that. With the DHT and ratio settings now implemented, I don't think there's anything left to do for private tracker support.

**Comment by nix87** [comment]
I think I know where the problmem is but it's not something what Quasar should and can do.

**Comment by scakemyer** [comment]
Reopening #38 until we know for sure that private trackers are working properly. @nix87 I wouldn't mind you telling where you think the problem is.

**Comment by nix87** [comment]
I'm not sure how that works with Quasar. I'm really sad cause my ignorance about programming so I can't give proper help.:( 
I thought that providers somehow need to take passkey from private trackers how you will get permission for download. Passkey is some kind of ID for your account on private trackers, every user have one and with that system knows when you download their torrent, when you seed their torrent, when you h'n'r their torrent etc. But that mine theory is probably incorrect.
I thought those credentials needs to be taken by providers not Quasar but probably I'm wrong about that because if Quasar take torrents and download them like on your regular client why he can't take those credentials with torrent file like in uTorrent e.g? In providers you can enter your username and password and it's equivalent to registration on tracker so when you register and download some torrent file you should take all those credentials with torrent file and you should download without problem right?
I tried to download torrents from private trackers and it didn't work. When I download torrent file from public tracker and insert file in Quasar it starts downloading right away, but with privates it won't start download.
