### ISSUE TITLE
Must restart kodi before using Quasar error

### ISSUE THREAD

**Issue by Norin-Radd** [scakemyer/plugin.video.quasar#363]
Quasar keeps giving that message on the pi 2, kodi is restarted and it doesnt work, sometimes it says something about the binaries (i forgot what was the message and now is not showing that).

It has happened to at least 3 people as i see posted on the official forum

would appreciate some help

**Comment by scakemyer** [comment]
No logs, no help. The only metrics I have about Quasar are from the new TMDB API key, and it's reporting over 100,000 unique users. Let's say it's actually 1/5 of that because of multiple IPs per user, and 5% are using a Raspberry Pi. That's still over a thousand people that beg to differ with you three stooges that didn't read the release notes.
