### ISSUE TITLE
Add support for Providers with Private Trackers

### ISSUE THREAD

**Issue by iCanuck** [scakemyer/plugin.video.quasar#38]
I don't know what the previous issues were with creating Providers for Private Trackers but I know mancuniancol had tried in the past.

**Comment by dlucic** [comment]
Do private trackers support Quasar as a torrent client? :O

**Comment by mancuniancol** [comment]
Usually, the problem is to keep the cookies from the session. If it is a way to send that information from the provider, Quasar can download the information without problem.  It is the same way if you copy the link from the browser to incognito session.  It won't download.  Meanwhile, if you use another tab in the browser that you opened the session, it will download

**Comment by mancuniancol** [comment]
I've been able to overpass that problem when the player can play from local torrents.  But, I've already asked that feature here.

**Comment by Magic815** [comment]
While I think this would be a great addition, I think the implementation needs to be thought through extremely well if added.

Some issues I could see arising:
1. Quasar is not on the "trusted clients" list for any private trackers that I belong to. (This is the point dlucic is making above). We don't want users banned by private trackers because they're using Quasar.
2. Ratio risk. With private trackers, you're typically long-term seeding the file (if not perma seeding) for ratio reasons. We have the ability to keep or delete the stream after watching, but we'd probably need an additional layer to that feature where private tracker torrents get kept by default (regardless of the main 'delete'/'keep' setting that is selected).
3. To effectively let private torrents perma-seed, you'd want Quasar to be able to hardlink or symlink the files. That way you could have a link of the file properly sorted/renamed for Kodi's use, but you also wouldn't be messing with the torrent file so that you were getting proper seeding credit with the tracker. At some point, Quasar with all of the properly implemented features would become almost a clone of CouchPotato or Sonarr. What's the reason for not just using those as they exist already and work really well?

**Comment by nix87** [comment]
Yes, while this can be turning point in streaming torrents through Kodi, the developers need to make some additional stuff if we want for this to work properly.

E.g. if you want to watch some video from private trackers Quasar need to be able keep seeding that torrent after download at least 72h from moment you finish download. As I know so far Quasar seeding only while you watch video after you finish watching it stops and if you stop seeding after such a short period then it counts like hnr (hit & run) and that is strictly forbidden at private trackers. I know that Torrenter have option to keep seeding after watching so I belive Quasar can have that option as wel.

For maintaing ratio that shouldn't be big problem as you can borrow seedbox for month and make TB's of uploads on couple privites.

But I think the biggest problem will be client who download stuff from their trackers. Every private tracker have client list, what magic mentioned, which is allowed. If you download their torrent with some client which isn't on their list you are in trouble and could face the ban of yours acc. 

I also really would like for this to work on Quasar but I think it will need a lot of work from developers to make that possible.

**Comment by mancuniancol** [comment]
Then, it is too complicated to implement that at this point.

**Comment by nix87** [comment]
Well I'm afraid it will be hard to implement that but anyway developers could try though when they have free time. But even if they can't make it work people need to be satisfied with what they got.

There is something which can save the thing a bit i supppose. On web there aren't only strictly private torrent trackers like hdbits, hd-torrents, btn, awesomehd, freshon, filelist, torrentleach, ptp and others. 
There are trackers who also are solid, not that good like those above but not that riggid when it comes about rules like e.g. zamunda, hd-space, nethd, hclub, torrentday, bitsoup, privitehd (ex publichd)... Those trackers are not demanding too much and all what matters is to stay away from "hit & run". Maybe with this trackers Quasar could work successfully?

**Comment by lyanko** [comment]
Hi it's lyanko again :) I notice that Quasar development is fast again so I wonder when this issue will come to order? xD I have a couple of very good trackers and really can't wait to use them on Quasar.
Thanks in advance and really like the fast progress of the addon :)

**Comment by scakemyer** [comment]
Honestly I don't think there's anything left to do in Quasar, as long as providers pass the required cookies, that the trackers allow Quasar, that you turn off DHT and set proper sharing limits it should be working already.

**Comment by lyanko** [comment]
Ok I will give it a try if it's same old problem then I will post log file. Maybe that could help :)

**Comment by lyanko** [comment]
Ok, here is the log, I hope I did it right :)
https://paste.ubuntu.com/23667018/

I tried to play one torrent from one of the providers for private tracker and it just stuck on finding.

**Comment by scakemyer** [comment]
You did, but as I suspected this is a provider issue, at least in this case. Removing the link to your log just to make sure we don't get this issue blocked.

**Comment by scakemyer** [comment]
I can however point out that the provider was returning a magnet link from its own service when it should probably be torrent files only for private trackers, and that there was no authentication cookie either, which makes it impossible for Quasar to access the torrent.

**Comment by lyanko** [comment]
Ok, no problem ;) Can I make log file from playing this same torrent via YATP (another torrent streaming addon). Just for you to see if there is something different between two addons? Cause on YATP with same provider this torrent works.

**Comment by lyanko** [comment]
Here is the log when I play torrent from YATP with same provider.

https://paste.ubuntu.com/23667076/

**Comment by lyanko** [comment]
Yes private trackers don't work with magnet links only torrent files.

**Comment by scakemyer** [comment]
So yeah there's the first issue. Quasar is getting a magnet link and YATP is getting the torrent file... Try using the context menu thing, maybe Quasar will also get the torrent file instead. Once the provider behaves the same way when searching from Quasar it should work just as well.

**Comment by lyanko** [comment]
I just tried and through context manu and same blocking thing. http://paste.ubuntu.com/23667146/

**Comment by lyanko** [comment]
It's a last time i will post logs without someone asking. I did it another comparison scakemyer. I download torrent file from one private tracker and then I play it through both play torrent options in addon so there isn't any provider involved. And here is the result.

Quasar - http://paste.ubuntu.com/23667315/
YATP - http://paste.ubuntu.com/23667305/

**Comment by scakemyer** [comment]
Enjoy in v0.9.46 :) xmas present for you folks

**Comment by nix87** [comment]
Amazing addition really. I forgot about this a bit honestly but I keept hope that this will be added soon day. xD And if it even better it's right infront Christmas... magic. :D

**Comment by lyanko** [comment]
Yeeeees!!! I know it was possible. :) Million thanks man this is huge thing for Quasar.

**Comment by tomtomclub** [comment]
Merry Christmas  scakemyer

**Comment by herrwusel** [comment]
Thanks scakemyer! Enjoy your coffee ;)

**Comment by unster** [comment]
@scakemyer are you aware of IPTorrents tracker plugin?
