### ISSUE TITLE
Third party Subs addon doesn`t work

### ISSUE THREAD

**Issue by tistasis** [scakemyer/plugin.video.quasar#395]
This addon is ver good, but the third party subs addons dont work. I search any sub and nothing is found, when the subtitules exists in the sites addon.

**Comment by palula** [comment]
I've downloaded OpenSubtitles from the Kodi subtitles and everything is working fine.

**Comment by tistasis** [comment]
I will try that one, the Tusbutitulo addon is the one that doesnt work with quasar and work with other addons

**Comment by palula** [comment]
You can even setup the main subtitles addon in Kodi for it to work widely inside the environment, which in case will work with Quasar also...

**Comment by m4xc4v413r4** [comment]
Wait a sec... why are you downloading the opensubtitles addon when it's already built in Quasar?!

**Comment by tistasis** [comment]
i configure everything but, when its time to choose a sub the addon doesnt work . I know that quasar already has the opensubtitle addon but, it isnt as good as tusubtitlo ( for spanish subs)

**Comment by nix87** [comment]
Mine additional subtitle addon along Quasar's work very well.

**Comment by scakemyer** [comment]
So which is it? Is there really an issue here?

**Comment by tistasis** [comment]
Nix87 what sub addon are you using? I use tusubtitulo and aregenteam and any of those work for me, only the quasar one but like I said before for spanish subs  is not the best because sometimes open subtitles takes a long time to upload a spanish sub

**Comment by nix87** [comment]
I'm using Titlovi addon for Serbian or EX-Yu (Ballkan's) sub's and that working fine for me. Did you tried those spanish language sub addons outside of Quasar, just on Kodi? Maybe it's problem in them I don't know?
I used to have problems with podnapisi addon with Pulsar but when i tried outside of Pulsar I realized it's not only Pulsar addon had problem in whole Kodi.

Oppensubtitles is pretty good source for sub's though it gives me a lot Serbian or other Ex-Yu subtitles for everything.. movies, tv shows, docu's.. everything so it's strange that huge language speaking area like Spanish is haven't got good results on that site? 

I even set Quasar subtitles as default for both movies and tv shows and I can't aks for more ;)

**Comment by nix87** [comment]
You know what, now I'm going to slep xD but tomorrow I will try those spanish subtitles addons and I will see what results I will get with them ;)

**Comment by tistasis** [comment]
Yes I tried those addons outside Quasar and worked fine, but in Quasar doesnt look for nothing neither manually or automatic.

Thanks for the help

**Comment by ShlomiD83** [comment]
As we said before, since we switched to tmdb for tv shows as well third party addons dont find subtitles automatically, only manual search.

**Comment by deusbraga** [comment]
I think this has already been mentioned before but with third party subtitles addons quasar doesn't work well, I can't figure ou if it's sending the real title but translated or nothing at all. This happens with legendas.tv addon

**Comment by scakemyer** [comment]
Sorry guys but this isn't going anywhere, saying this and that add-on isn't working. Many are reporting (not just here) theirs are working fine, and those that don't aren't providing any useful information or details whatsoever besides the typical "it dun wurk mang". Quasar doesn't "send titles", nor does any other add-on in Kodi. There's what's called InfoLabels in list items, which allow skins and other add-ons to display the various informations and do other things like search subtitles. There's nothing special about Quasar here. The only list items that are sure not to have any infolabels are those in the Torrents section, which you can notice since they don't have titles, thumbnails or anything, they're just the list of active (or paused) torrents from libtorrent. So maybe you're playing your files from there and your third-party subtitle add-on is naturally not getting any info from it, maybe you're not, but either way no one is providing any useful detail. Logs, exact steps taken, something. It's the least you can do considering I can end up spending hours or days trying to solve a single valid issue.

**Comment by ShlomiD83** [comment]
hey @scakemyer, here's a fresh log. played 1 movie and 1 tv show episode to compare.
the movie found subtitles on 2 subtitle addons and the tv show episode found none on all 3 addons.
i hope you'll find the answer..
http://xbmclogs.com/p22ykq9yf

**Comment by ShlomiD83** [comment]
it seems it's searching for whatever the OSD is showing, if it's an episode name it will never find it.

**Comment by m4xc4v413r4** [comment]
I'll test this out in a couple of hours but apparently on that sub add-on, it's searching for the episode title only which I don't know if is standard but even if it is, it isn't a good idea.

What bothers me is that I use the built in search and I get subs every single time in every single movie or tvshows, unless, it's a brand new episode that just came out like hours ago, which is normal since it takes time to make subtitles and to translate subtitles, so I never really expect to find any in that situation.

**Comment by ShlomiD83** [comment]
manual search always works, that's the point. the videoplayer window isn't getting the right InfoLabels for it to search for show name, season number and episode number (The flash s02e15) for example.

**Comment by m4xc4v413r4** [comment]
And my point was, the built in search works automatically, not just with
manual search, so unless it's getting different info I don't really get why
the others won't work when given the same info.
Em 16/03/2016 13:11, "ShlomiD83" <notifications@github.com> escreveu:

**Comment by ShlomiD83** [comment]
did u mean the quasar subtitle addon? maybe because it's a built-in addon it gets different info..

**Comment by m4xc4v413r4** [comment]
yes, i meant the subtitle search built-in quasar which uses opensubtitles.

Anyway i checked and the only thing i found that looks strange is that in all of those addons you used, the field "tvshow" is blank in the query.

On the movie, since the name of the movie goes into the "title" field, it uses that and it's ok, an easy find.
```Python
14:42:38 T:1864   DEBUG: ### [Subscenter.org] - Item before cleaning:
                                                {'episode': '', 'temp': False, 'title': 'Jurassic World', 'preferredlanguage': 'heb', 'season': '', 'year': '', 'rar': False, 'tvshow': '', 'file_original_path': u'http://localhost:65251/files/Jurassic.World.2015.1080p.BluRay.x264-SPARKS[hotpena]/Jurassic.World.2015.1080p.BluRay.x264-SPARKS.mkv', '3let_language': ['heb']}
```

On tvshows, the "title" field only has the episode name, the "tvshow" field is blank, and for some reason the addon is using just the "title" field.
```Python
14:41:01 T:5600   DEBUG: ### [Subscenter.org] - {'episode': '15', 'temp': True, 'title': u'King Shark', 'preferredlanguage': 'heb', 'season': '2', 'year': '', 'rar': False, 'tvshow': u'', 'file_original_path': u'http://localhost:65251/files/The.Flash.2014.S02E15.720p.HDTV.X264-DIMENSION[rarbg]/The.Flash.2014.S02E15.720p.HDTV.X264-DIMENSION.mkv', '3let_language': ['heb']}
```

**Comment by scakemyer** [comment]
It seems those add-ons are the culprits, because we **are** setting the `TVShowTitle` InfoLabel.

**Comment by ShlomiD83** [comment]
So How did it work before the tmdb switch?

**Comment by scakemyer** [comment]
The InfoLabels were supposed to be the same as they were, but I screwed up for `TVShowTitle`, using `show.Title` instead of `show.OriginalName`... Thanks for the pointers @m4xc4v413r4, that helped a lot. I still don't get how it managed to work with the built-in search since it's reading the same InfoLabels, which was a bit misleading, but at least we finally got to the bottom of this, no matter how simple the fix actually was.

**Comment by ShlomiD83** [comment]
it works, thnx..
