### ISSUE TITLE
Feature request: Different download paths depending upon video type

### ISSUE THREAD

**Issue by bodangren** [scakemyer/plugin.video.quasar#403]
Since the system knows where the file is a movie or TV video, can there be separate paths for these two? Then I could set the paths for auto sorting into the library later or live dangerously and just set the library paths as the download locations. TIA!

**Comment by bodangren** [comment]
Dup. Sorry

**Comment by scakemyer** [comment]
Yep, #97 ;) I appreciate the self-closing of a dup, very refreshing. Adding Trakt scrobble actually provided most of what was missing for this, being the type of media sent to the torrent player, where it was previously just dumbly playing a magnet uri. There's still a few things I need to think about for this since it's never as simple as it looks, but it'll definitely make its way sooner than later.

**Comment by bodangren** [comment]
Thanks for the information. I appreciate all your hard work!
