### ISSUE TITLE
Cannot update quasar demon

### ISSUE THREAD

**Issue by luispabon** [scakemyer/plugin.video.quasar#406]
http://hastebin.com/nipacocixe.tex

It leaves Quasar in an unusable state, asks for Kodi to be restarted which I've of course done a number of times to no avail.

**Comment by luispabon** [comment]
If I were tio venture a guess based on the logs, the fact the quasar daemon has started is causing the .exe to be locked by the OS hence it cannot be replaced.

**Comment by m4xc4v413r4** [comment]
If it were so, it wouldn't update for anyone and it does update just fine...

Do a manual update.
And post logs on http://xbmclogs.com/ please

**Comment by luispabon** [comment]
Still, the logs are quite clear on what's going on. There must be corner cases in which this situation happens which can possibly be coded around.

**Comment by luispabon** [comment]
I can of course update manually, but that would do nothing to help test a possible fix.

**Comment by m4xc4v413r4** [comment]
I didn't mean forever.
I don't really understand why it's blocking you from doing changes on appdata. Quasar also starts before the update on my machines and it still updates and then starts again.

**Comment by luispabon** [comment]
Testing a possible fix for you, that's what. There's a corner case that breaks the update system and it will be very difficult to replicate and fix if it's not happening to other people active on github. If I fix manually, there goes the possibility of testing it.

**Comment by scakemyer** [comment]
In this case, yes, you should stop the quasar.exe process and update manually. Then provide logs when the upgrade process actually happens, because these ones are after the fact. It's a good start, but there's no way to know what actually happened while upgrading the add-on. Maybe Kodi crashed and never sent the shutdown signal to Quasar, and since this is Windows we're left with a mess and a lone process preventing the next launch.
