### ISSUE TITLE
Add search history to Quasar Kodi addon

### ISSUE THREAD

**Issue by shaharsol** [scakemyer/plugin.video.quasar#411]
I've decided to utilize [CodeMill](http://codemill.io) to offer $20 to anyone who will add this feature to scakemyer/plugin.video.quasar:

Many Kodi addons have a search history functionality. When a user clicks "search", instead of immediately opening the search dialog, they are given to choose between "new search" and "search history". 

I'd like to see the same (very missing) functionality in Quasar.

In order to develop this and earn $20, please proceed to the [task page at CodeMill](http://codemill.io/task/56ea6bb6a7e2c103005dbb35).

The work will be done on my own fork, and when it's finished I will send a pull request to scakemyer/plugin.video.quasar so the entire community can enjoy this feature. This will be my contribution.

**Comment by scakemyer** [comment]
That was cute.

**Comment by shaharsol** [comment]
Why not?

**Comment by Filosofos** [comment]
It seems that there is an error with the search, because although it brings back results, the mask keeps asking for an entry.
`ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.quasar/shows/search) failed`
`ERROR: CPythonInvoker(96, /storage/.kodi/addons/plugin.video.quasar/navigation.py): script didn't stop in 5 seconds - let's kill it`
Log file [here](http://goo.gl/bDGksp)
