### ISSUE TITLE
Option to send complete downloads to it's folder

### ISSUE THREAD

**Issue by joaohkfaria** [scakemyer/plugin.video.quasar#440]
Please, it'll be incredibly useful if there's an option when the file finishes the download, it automatically go to the Movie folder (and not stay on the download folder). 
This is useful for people who use subtitles and for those who want to keep there library organised.

**Comment by scakemyer** [comment]
See #97, there's no such thing as just a Movies folder in Kodi, you set many paths with different content types, which might or might not be writable.

**Comment by unster** [comment]
Hi @scakemyer, I came here from [#536](https://github.com/scakemyer/plugin.video.quasar/issues/536). Do I understand correctly, this idea is not a solution for people having small internal memory and big external cards/drives?

For me the biggest issue is that I can't download anything bigger than 2-3GB due to 8GB internal memory... even I have 64GB card mounted.

**Comment by scakemyer** [comment]
No, this will be *the* solution to both having small internal memory, *and* keeping our library well organized by moving finished downloads where we want them automatically.

**Comment by unster** [comment]
@scakemyer thanks, but may you explain me something, because I'm not getting it right...

1. In my case, when I select 4GB torrent file - after a moment I get an information about "not enough space" and download is canceled. How will it help for that?
2. Let's assume issue from point 1 is solved. Playback starts when 20% of file is buffered (~800MB). How this file will be moved during playback (when it reach 4GB, which shouldn't even fit to my free space at internal memory).

I thinks this idea won't solve that cases.

**Comment by elgatito** [comment]
You can root your android device and make a mount to extrenal hdd.

**Comment by scakemyer** [comment]
1. It won't, if you have only 4GB, you're f***ed anyway. Get a $30 pi3 and sell the shitbox you have now, or as @elgatito just mentioned, root the thing.
2. It won't either, it can't, and won't ever work that way.

**Comment by heartlogic** [comment]
Or put LibreELEC in TV box where you can mount a path in OS before Kodi starts...

**Comment by scakemyer** [comment]
Quick update on this one, I'm 80% done implementing it, with mostly just proper moving/copying of files/directories themselves left (you can't imagine how insanely complicated that last part actually is... what? moving files is hard? well yes, yes it is). So I'd need beta-testers on all platforms (mostly Android) sooner than later since this is one feature I simply cannot risk to be breaking on first release. It'll also be adding some much needed basis for a more complete fix to #739, ie. getting movie/show names in the player when starting them from the torrents list or the WebUI.

**Comment by scakemyer** [comment]
Since I'm getting no response for Android beta-testers, and it's an optional feature and setting, I'll release it anyway and go from there. After all we're still pre-v1.0...

**Comment by KillerJoeBR** [comment]
Hi  @scakemyer . It's carnaval here in Brazil, so i was away and didn't see this. Anyway, does this feature works during playback? Cause if so it will probabl cause slowdowns or maybe even crashes. Or is it smart enough to copy/move after playback? Or maybe the user can set the time to do it? Like at Quasar start, or idle time or something like that? Can i download quasar right now and test it? or does it need futher implementions to work?

Thanks

**Comment by scakemyer** [comment]
You sound like you're high with all those questions back-to-back... It'll be in the next release, and yes, it waits for playback to stop, whether it's from Quasar or not so as to not cause any slowdowns, and only moves files after 'Seed time limit' has passed. You can see the help messages in the first commit, that will show up when you enable the feature. It even cleans up strm files that were added to your library after moving files to prevent duplicates, so your movies/episodes become the ones you downloaded.

**Comment by KillerJoeBR** [comment]
Sounds great! And can it move the files to a samba share? Not OS mounted.

**Comment by scakemyer** [comment]
Nope, it's one of the reasons it hasn't been released yet too since I need to handle that to prevent all of you that are going to try it anyway ;) As line 815 of `service.go` says:
```
// TODO generic "valid" path checker, ie. no 'nfs:/' and 'smb:/' paths
```
