### ISSUE TITLE
Disable All Provider/Enable All Provider

### ISSUE THREAD

**Issue by compyy** [scakemyer/plugin.video.quasar#493]
Hello,

Welcome Back :) can you add one more feature in provider manager to disable all providers and enable all providers, sometimes i have to disable quasar and i can't do it without going disabling each provider one by one, this can solve big problem for me thanks.

**Comment by bluenote73** [comment]
@compyy what would be super helpful is for you to raise a request with the kodi devs because their implementation of dependencies in addons is not optimal.  It will complain, when you try to disable an addon with enabled dependencies, but not offer to do anything about it.   There's other addons this comes up with, but I can't actually think of them ATM.

**Comment by scakemyer** [comment]
It's actually a valid request here, already thought about adding it and should be straightforward enough.

**Comment by scakemyer** [comment]
No longer that useful with Magnetic, pushing to v1.0...

**Comment by m4xc4v413r4** [comment]
I haven't gotten into the Magnetic train yet, is it really a valid replacement to normal providers? Like, it limits me to one source, I don't see how that's good.

**Comment by scakemyer** [comment]
I'd say you should wait a little more... ;)
