### ISSUE TITLE
Put.io integration

### ISSUE THREAD

**Issue by CrazyGentleMan** [scakemyer/plugin.video.quasar#522]
Quasar look for media then the providers bring torrents, it would be awesome if Quasar can send the selected torrent to put.io account and then stream it from their servers.

**Comment by nix87** [comment]
Quasar is currently but also maybe premanently (still reamin to be seen) stopped with development and it's been a while when developer showed last time here. 

But I'm sure this thing put.io will never be Quasar's part because Kodi's legal rules. You should try at iStream addon forum to ask for implementation of put.io service cause they have already similiar thing implemented with furk.net or easynews.

**Comment by scakemyer** [comment]
Nope.
