### ISSUE TITLE
Looking for contributors

### ISSUE THREAD

**Issue by scakemyer** [scakemyer/plugin.video.quasar#534]
As you probably noticed I've been away for the past few months, and while I'm back and would've made fixes if the add-on had stopped working, having other developers contribute to the project would go a long way to make sure it keeps going and new features get implemented.

@i96751414 Are you still around?
@dimitriss I see you've made progress with libtorrent 1.1, any chance you could contribute that upgrade?

**Comment by scakemyer** [comment]
Thanks for all the thumbs up, I'll just keep improving the add-on whether or not other contributors join in.

**Comment by m4xc4v413r4** [comment]
I would love to help out, I'll try to get more acquainted with Kodi's API and with your code on my free time. I've also been away for some months because of work :(

Too bad the guys that could really do a lot (mostly because they already did a lot of work on kodi plugins) seem to not be around as much these days, everyone is kinda disappearing or whatever.
I guess everyone has their own things to do :) We can't really expect them not to.
