### ISSUE TITLE
Searching for torrent shows wrong series (name overlap)

### ISSUE THREAD

**Issue by marcelmah** [scakemyer/plugin.video.quasar#543]
I'm starting to watch the walking dead series, from season 1 (yes I know I'm late...).

When searching for S01E01 90% of the results are for the spin-off **Fear** the walking dead, only the last two items are for the walking dead.

**Comment by bluenote73** [comment]
This is happening because that's what the torrent indexer is returning.   So if you can't get better search results from the web interface of whatever provider you are using, there's nothing that's going to help on quasar side.  Complain to the indexer or figure out how to use their interface to get better results, then talk to the indexer addon provider.
