### ISSUE TITLE
Possible problem with the version number. 

### ISSUE THREAD

**Issue by mancuniancol** [scakemyer/plugin.video.quasar#55]
I've been reported by some users that they have been returned to beta version after installed the version 0.9.1.
It seems that kodi believes that new version, 0.9.1, is lower version that version 0.9.1-beta.  Just for string order. . I am wondering if it possible to jump to version 0.9.2. Or add a 0.9.1c. But, I think it is better idea just jump to the next number. At work, we use odd numbers for official release and even for internals.

**Comment by scakemyer** [comment]
Yes I'm aware of this, removed the dot in beta versions hoping Kodi would understand those better, but it seems like it's not following its own rules regarding version numbers for add-ons. I've bumped the milestones to leave some room for smaller updates during the next few weeks. I'd like to get a few fixes in before bumping the version number again though.

On a side note, that issue would not happen if Quasar wasn't in third-party repositories, and users were just using the official built-in GitHub-based repository, since pre-release updates are ignored (when the setting to get them isn't enabled). If you're distributing it through yours, could I ask you to remove it please? I'll also be adding a checksum verification in the binary, so at least users will be notified if the version they're getting has been tampered with, not that I think you're doing so but others might not be so honest.

**Comment by mancuniancol** [comment]
I will try to speak with the administrator.  I only send my zips with the updates.  But, I don't have any right to do anything else.

But, usually it is complicated to remove something.  Because, it is linked to balance the mirrors.  The idea was to have the lowest version and when the people install that version, it will install the quasar official repo and the version will be updated automatic. But, in this case, it is doing the opposite.

I will ask if it is possible to change the beta for the 0.9.1.  Then it will work in the way that I've explained.  Of course, it will fix in the moment that you release version 0.9.2.

I will keep you posted.  Sometimes it takes couple days to do that kind of changes.

**Comment by scakemyer** [comment]
Sounds good, thanks! v0.9.2 is coming up in about half an hour.

**Comment by mancuniancol** [comment]
Wow.  :) . I don't miss Pulsar at all. It was eternal to wait for an update. 
I will close this issue, because I think it will be fixed with version 0.9.2.

**Comment by scakemyer** [comment]
It will be even more fixed in 0.9.3, hopefully ;)

**Comment by mancuniancol** [comment]
I just want to confirm that it is working already. Cool

**Comment by scakemyer** [comment]
Yeah, but see #58 (way too much logs in this one though). I've had the exact same issue over here, which happens if the built-in repository catches the update before the zip is uploaded...

**Comment by mancuniancol** [comment]
I see. Let me know if I ask to remove or not Quasar installers from the repo

**Comment by scakemyer** [comment]
I understand it makes it easier for folks to install it the first time, instead of having to install from zip. The built-in repo should always be up-to-date sooner anyway after that, so it shouldn't be a big issue. Third-party repositories bring their own share of risk in the first place so I don't think we should do anything about it really. Thanks for offering to ask though :)
