### ISSUE TITLE
Add option to disable Quasar subtitles  

### ISSUE THREAD

**Issue by Pinhastest** [scakemyer/plugin.video.quasar#560]
Add option to disable Quasar subtitles. Some times the AutoSubs service doesn't work because of Quasar subtitles have some wrong subtitles to use

**Comment by scakemyer** [comment]
I've looked into this and it's unfortunately not possible to disable the subtitles extension point. I tried not returning anything also but Kodi still shows Quasar as a subtitle provider anyway. Closing as wontfix, if someone finds a solution I'll be happy to implement it, but otherwise the subtitles have been fixed and are staying, sorry about that.

**Comment by Pinhastest** [comment]
Thanks for your time and dedication for making this addon so good

**Comment by scakemyer** [comment]
And thanks for your patience ;) Next release will be pretty amazing, a lot faster, much lower cpu usage, fixed memory leaks, useful new features, a lot more reliable and well polished :) That's my sales pitch for the new year.
