### ISSUE TITLE
Quasar 0.9.2 crashes while 0.9.1 worked fine

### ISSUE THREAD

**Issue by dtsexpert** [scakemyer/plugin.video.quasar#58]
Kodi auto update to 0.9.2 and it crashes on my Android 5.1.1.
0.9.1 worked fine. Check the 0.9.2 but don't see any option to roll back :(
pastebin http://pastebin.com/Y6TtTzDe

**Comment by scakemyer** [comment]
Actually had the same error also, tracked it down to the built-in repository using tags instead of releases, and defaulting to making a zip with no binaries... I don't know what Steeve was thinking there because this causes the exact same issue as users using the `Download ZIP` button and getting an add-on that is missing the binaries... Fixed in scakemyer/quasar@e3f5720 and 0.9.3 will be released in less than 30 minutes.

**Comment by scakemyer** [comment]
Meanwhile you can just install it from zip, that should work.
