### ISSUE TITLE
Downloading path in external storage

### ISSUE THREAD

**Issue by ijose2** [scakemyer/plugin.video.quasar#608]
Hello,

I've have an issue, when I select as destination folder an usb stick or and sdcard. I'm using Android 6.0 tv box.
When I choose a folder in external storage, Kodi show an error indicating the name of new folder or the new location is wrong typed.

Has anybody this problem?

**Comment by heartlogic** [comment]
Quasar cannot use an external storage as a USB stick or an SD Card because of the limitations of the add-on... Moreover in Android Marshmallow the permissions are more strict because of the O/S...

In LibreELEC you can use an external storage as a NAS only if you mount it before Kodi loads...

Please correct me if i am wrong...

**Comment by scakemyer** [comment]
That's about it yes, they're limitations of libtorrent 1.0.x, mentioned countless times in other issues. Working on the upgrade to 1.1.1, which should hopefully make it possible to use external storage, but the requirement to be mounted by the OS will remain.

**Comment by ijose2** [comment]
It's a shame, since most android tv, have little free space on the internal storage. This makes the use of the addon somewhat less. Wait for the update to see that it works. Thank you.
