### ISSUE TITLE
The Dowload Path to Nas on 0.9.49 Version

### ISSUE THREAD

**Issue by trongthuan0311** [scakemyer/plugin.video.quasar#621]
I just test 0.9.49 that version can set dowload path to Nas but i got unlucky, This version can't locate the dowload path to Nas ( Linksys EA4500 with usb input ). Althouht i set the dowload path in setting buf Quasar alway dowload the movie to internal storage ( my Fire tv ) or drop dowload speed to 0kb/s
The firetv have had a narrow space . Thanks you awsome work

**Comment by KillerJoeBR** [comment]
It is not as simple as that to use Nas storage.  You first need to mount the Nas drive to your android system,  so it is basically another folder in your android device.  That's all I know.  How to mount Nas you need a script or something like that.  (I don't know how)

**Comment by scakemyer** [comment]
As @KillerJoeBR said, and mentioned in the release notes, your NAS has to be mounted by the OS to appear like a regular folder. Even then, performance might not be up to it, either because of current libtorrent storage settings, the actual NAS setup you're using or the device itself, especially on low-power devices. I've tried on Linux with tuned storage settings (which might land in 0.9.50), and while it was painfully slow at first speeds actually got up to near normal levels after a little while, but I still need to compare the same setup with the current 0.9.49 release.
Closing since this is about your actual path to your NAS, which most probably won't ever be supported.
