### ISSUE TITLE
Less torrent results for private providers, wrong resolution and torrent size in choose stream dialog

### ISSUE THREAD

**Issue by nix87** [scakemyer/plugin.video.quasar#634]
Hi Scakemyer I will show some pictures and comparison between Quasar's choose stream dialog and Magnetizer choose stream dialog, I hope that is ok. I just want to know if it's Quasar fault for this and if there is fix for it?

Ok here we go....

Fisrts of all Quasar and Magnetizer don't match results never. Then Quasar have problems with resolution replacement. E.g. it will show you 1080p resolution and name of torrent but movie size will be 720p. I will picture for you to show better...

...

So with public providers results are ok but with privates there is less torrents then on tracker itself and something cause interfering between resolutions or size of torrents.

I hope I showed good enough what I think the problem is :) Also if you need some logs for this beside pictures please let me know ;)

PS: I'm sorry for this type of post. I don't know why is that I didn't bold anything or something like that???

**Comment by scakemyer** [comment]
First of all, please don't post issues about providers here, I really do not appreciate that and you're only risking the safety of this project on GitHub.

Let me make something else very clear: **Quasar is content neutral and does NOT provide links or "results"**

Quasar shows the results it gets, and you might see less results when it receives invalid ones, or ones it can't reach like from private trackers if they're not properly sent to it, and this is the case here. Private trackers work perfectly well now, and I can assure you the real mess is on the other side. There's still many bugs in Quasar, but this is not one of them. The new libtorrent version throws and `invalid port` error on URLs it receives from that hackish workaround used by your providers, when it should be sending a proper URL with cookies, or even just a file path. I also won't be patching libtorrent just to allow weird ports in URLs when they shouldn't be there in the first place.

As for resolution and size, you seem to be mixing up the two of them. 720p is a resolution and 3GB is a size. There *was* a resolution parsing bug that was finally ~~fixed~~ burned to the ground in 0.9.51 (#261), but sizes are displayed as-is, which means if a result says 3GB, that's what Quasar received with the result, and if it's wrong or doesn't match, it means it's receiving wrong results and the bug is on the other side also. I hope this clears things up.

**Comment by nix87** [comment]
Yes perfectly.

Sorry I didn't knew it was forbidden to talk about *that* here. I knew it was forbidden at Kodi forum but here not.

Don't worry it won't happen again, and beside this Quasar indeed works perfect with any kind of torrents now :)
