### ISSUE TITLE
[Question] What should be changed to support NAS mounted from inside Kodi

### ISSUE THREAD

**Issue by hugochinchilla** [scakemyer/plugin.video.quasar#641]
I've seen a lot of threads talking about how quasar cannot handle NAS because of libtorrent limitations.

I would like to help in changing this but as I'm not familiar with quasar code nor libtorrent I would like to have some guidance, could you elaborate a bit more on why is not possible?

I understand that performance will be sub-optimal, but to my understanding, if Quasar can download to a NAS if mounted from outside Kodi, it should be possible to make it work with a NAS mounted inside Kodi.

**Comment by scakemyer** [comment]
It's been said before, it is perfectly possible with an OS-mounted NAS path, it's even right on front page readme. I'm not sure how well it worked with libtorrent 1.0.x, but with the upgrade to libtorrent 1.1, I've had no trouble using a fast enough NAS. You might want to enable the tuned storage setting to save on read/writes if you can spare more RAM.

**Comment by hugochinchilla** [comment]
Sorry @scakemyer if I did not myself clear enough.

I'am aware that Quasar supports and OS mounted NAS, but I run Kodi on an Android TV and sadly rooting it is not an option (I wish I could) so no OS mounting for me. I wan't this feature to work so bad that I've spent some time trying to hack my TV trying to root it, until I finally tought it could be easier and more helpfull for the community trying to fix this issue in Quasar itself.

So I will ask you one more time, if you could please explain what makes different for Quasar a NAS mounted from Kodi from a NAS mounted on OS level. Is it a Kodi issue? I want to help make it work but as you are familiar with the codebase you could give me some hints on what needs to be addressed for making it happen.

**Comment by scakemyer** [comment]
Alright, sorry I misunderstood your question. The problem is mostly that there's no way libtorrent can handle special Kodi paths, let alone regular network paths once those are "translated"; it only deals with local file storage and for very good reasons and simplicity, i.e. performance. That's basically all there is to it, you either have an OS-mounted path that libtorrent can read/write to like regular files, letting the OS deal with all the IO operations, and crossing fingers it can handle it, or nothing. I wish there was more to it, and a hint of a path to a solution but I'm afraid there isn't. Don't try to hack your Android TV box for it; get a better device like a pi3 or NUC, and sell that Android junk to someone else or make a boat anchor out of it; it'll be more useful that way. We'll keep trying to support Android as best as possible, but honestly that OS is broken by design and should be burned to the ground. Don't get sucked into "cheap" Android TV boxes only to try to make anything work properly on it, you'll be wasting your time, I know I did :(
So back to the point, there's nothing to fix in Quasar here, nor in libtorrent.

**Comment by hugochinchilla** [comment]
Thanks @scakemyer for your response.

my TV runs Android on it's own (no android box) I could get a PI for running Kodi but it's really nice to have it inside the TV just as any other app like Netflix or regular TV.

So let's recapitulate:

* inside Kodi network paths are special in some way, they can't be viewed as regular paths
* I have investigated and discovered that Kodi does not mount the NFS shares, it uses libnfs to access them.
* Quasar runs as a thread of Kodi, so it has rw permissions inside Kodi's sandbox (in Android)
* If I could write a Kodi addon which mounts the NFS share inside Kodi's sanbox quasar should be able to use it.

Am I right?

**Comment by scakemyer** [comment]
Unless I misunderstand what you'd be doing, I'm afraid that wouldn't work; libtorrent still wouldn't have a regular path to work with.
