### ISSUE TITLE
Multi-file torrents prioritize selected file but keep downloading other files

### ISSUE THREAD

**Issue by nix87** [scakemyer/plugin.video.quasar#647]
Currently when Quasar open multfile torrents he don't download only selected file from folder but whole folder.

## Expected Behavior

It should download only selected file from folder, and later seeding only that file.

## Current Behavior

It downloads whole folder.

## Possible Solution

Maybe add something which will make Quasar to ignore other files in folder, beside that one you choose ofc.

## Steps to Reproduce (for bugs)

1. Select multifile torrent from choose stream dialog
2. Quasar opens that and gives you all files from that folder (multi-file torrent)
3. Select file from that folder
4. Quasar play selected file but download whole folder

## Your Environment

* Version used: Quasar version 0.9.55
* Environment name and version (e.g. Kodi 15/16/17, SPMC, OSMC, OpenELEC): Kodi 17 RC2, Krypton
* Operating System and version (Android 4/5/6, Windows 7/8/10, macOS 10.11, Ubuntu 16.10): Win 7
* Link to Kodi debug log: /
<!--- See http://kodi.wiki/view/Log_file/Easy or paste to http://paste.ubuntu.com directly

**Comment by KillerJoeBR** [comment]
Another thing related to this one, is that right now you can't download an episode from a seasont pack if you don't have the available space for the whole pack instead of just the single episode you wanna watch it. So it would be nice if it was possible that Quasar could take into consideration only the storage necessary to see the selected file inside the season pack.

**Comment by scakemyer** [comment]
Good point, will try to fix that alongside this one. There was another issue about that iirc but can't seem to find it.
