### ISSUE TITLE
Quasar crashes while playing when saving resume data

### ISSUE THREAD

**Issue by johnnyslt** [scakemyer/plugin.video.quasar#653]
## Expected Behavior

Don't crash 

## Current Behavior

Crashes while playing, even if the torrent finished downloading 

## Steps to Reproduce (for bugs)

1. Select a episode from library 
2. Stream it
3.
4.

## Your Environment

* Version used: 0.9.56
* Environment name and version (e.g. Kodi 15/16/17, SPMC, OSMC, OpenELEC): Libreelec v7.90.010
* Operating System and version (Android 4/5/6, Windows 7/8/10, macOS 10.11, Ubuntu 16.10): rPi 3
* Link to Kodi debug log:

Happend two times :

1. http://sprunge.us/SXcZ
2. http://sprunge.us/aiOM

<!--- See http://kodi.wiki/view/Log_file/Easy or paste to http://paste.ubuntu.com directly

Btw, the file was downloaded from a private tracker

**Comment by scakemyer** [comment]
I'm fully aware of those saveResumeData crashes and been trying to fix this to no avail yet since the libtorrent upgrade, just look at the few changelog mentions and commit messages for the daemon. And before you ask, there's no going back to a previous libtorrent version, so consider this the highest bug on my priority list. I just had to keep moving forward with other issues and features in the meantime.
