### ISSUE TITLE
Quasar cause Nvidia Shield to reboot.

### ISSUE THREAD

**Issue by sask3m** [scakemyer/plugin.video.quasar#668]
Watching torrent with Quasar, Shield reboots at what would seem to be exactly when the movie is finished downloading.  Only time I ever see it reboot.    I have this log so should be right at the end.  Any ideas of the cause? Thanks.

**Comment by scakemyer** [comment]
I can see you changed the settings twice during that session, does it also happen when you don't? Although it usually keeps working, and libtorrent usually reloads new settings just fine, it's always a good idea to restart Kodi when you change settings. I also notice this line on the second settings change:
```
libtorrent   ▶ logAlerts        [0mportmap_error_alert: could not map port using UPnP: 500 Internal Server Error
```
So clearly it doesn't like getting reloaded more than once...

**Comment by scakemyer** [comment]
If you don't need UPnP/NATPMP altogether, I'd suggest you disable them in the settings. And restart Kodi afterwards ;)

**Comment by sask3m** [comment]
I'll disable UPnP/NATPMP and see what happens.  What exactly do they do as far as I'm concerned?   
     I haven't noticed a reboot every time but then again I haven't watched a lot lately.  
     
       Also what about these settings in general section:
   -background handling of torrents.
  - keep files after playback
  - ask to delete
I was thinking it was maybe one of those, so if I had changed a setting after d/ started it likely was one of those.  Thanks .:)

**Comment by scakemyer** [comment]
UPnP/NATPMP is what libtorrent uses to open the ports it needs on your router, allowing peers to connect back to you. It's not necessary for torrents to work, because as long as you can make outgoing connections, you'll be getting peers and opening those connections, but it also means you don't contribute as much to the swarm since you always have to be the one initiating the requests. So UPnP/NATPMP automates the process of devices behind a router to tell that router to reserve a port for it, and to forward requests on that port to it. It works fine for simple setups, but if you have a modem then a router or more, it won't do any good since you'd have to manually open ports in every one of them, and forward those ports from one to the other accordingly.

As for background handling/keep files/ask to delete, I understand how they can be confusing at the moment, and those options will be simplified very soon. Until then, background handling tells Quasar to keep downloading if you cancel buffering or want to use Quasar to seed for longer periods of time. Keep files after playback tells Quasar not to delete the torrent and files after streaming, or to keep the files and delete the torrent file itself if background handling is disabled. Ask to delete overrides your default Keep files after playback setting by asking you each time you stop playback whether or not you want to keep the files, again deleting only the torrent file or everything depending on your background handling setting. So as you see, every option has its own valid reason behind it, and while it can be hard to understand what's supposed to be doing what, there's no easy way to be able to do all of that without a few specific settings. I'm sure a mathematician would laugh at how easy it is to simplify the equation... but I'll eventually think of a good way to simplify this for the user, at worst by just clarifying the settings somehow.

**Comment by sask3m** [comment]
Thanks for the detailed explanation, I appreciate it very much. :)

**Comment by scakemyer** [comment]
You're welcome. Closing this for now as I also noticed the daemon actually shut down cleanly in your logs, so the signal came from Android and even Kodi quit properly without crashing. Will re-open if there's something we need to fix.
