### ISSUE TITLE
Quasar Ignores existing files when selecting the same torrent

### ISSUE THREAD

**Issue by ShlomiD83** [scakemyer/plugin.video.quasar#672]
## Expected Behavior

quasar should read existing file and start buffering after video playback has started from the point it stopped buffering the first time or not at all if the file has downloaded completely in the past.
## Current Behavior

quasar buffers the file from the beginning even tho it has sufficient MB to start video playback. and after the video has stated the buffring either stoppes if the file is complete on local HD or buffering droppes down to 0 KB if the file is not complete.
## Steps to Reproduce (for bugs)

1.choose to keep files after download\playback stoppes.
2.choose a movie\episode and stop after the initial buffring is compelte and video playback has started.
3.choose the same torrent again,
4.

## Your Environment
kodi 16.1
windows 7 64 bit

**Comment by scakemyer** [comment]
And that's why we need to get rid of the scary "background handling" setting... There's no actual issue here, libtorrent found the files and had to fully check them since your settings tell it to delete the torrent files and the resume data; it wasn't "re-buffering"... Just enable background handling to get the desired behavior, and here's an explanation I gave in another issue about those settings:
> As for background handling/keep files/ask to delete, I understand how they can be confusing at the moment, and those options will be simplified very soon. Until then, background handling tells Quasar to keep downloading if you cancel buffering or want to use Quasar to seed for longer periods of time. Keep files after playback tells Quasar not to delete the torrent and files after streaming, or to keep the files and delete the torrent file itself if background handling is disabled. Ask to delete overrides your default Keep files after playback setting by asking you each time you stop playback whether or not you want to keep the files, again deleting only the torrent file or everything depending on your background handling setting. So as you see, every option has its own valid reason behind it, and while it can be hard to understand what's supposed to be doing what, there's no easy way to be able to do all of that without a few specific settings. I'm sure a mathematician would laugh at how easy it is to simplify the equation... but I'll eventually think of a good way to simplify this for the user, at worst by just clarifying the settings somehow.

**Comment by ShlomiD83** [comment]
@scakemyer what about the speed droping to 0 when choosing to save files after playback/stop?
i checked with the option disabled and it worked fine, but when enabling it again the speed drops when choosing the same torrent again.

**Comment by scakemyer** [comment]
Choosing to save after playback doesn't change anything about when you start streaming, at all... no idea where you're getting that from, sorry. You'll have to explain your issue more clearly.

**Comment by ShlomiD83** [comment]
i have backgroung handling disabled. save files after playback enabled.
i choose the latest Colony episode, start streaming, stop playback, choose the same torrent again and click Yes to use the same torrent again. the prebuffering starts and so does the playback.
but then speed drops to 0 kBs and thats it.
i disabled the option to save files and tried the same process again and the speed was fine.
you need logs?

**Comment by scakemyer** [comment]
As I said, since you're keeping the files, but not saving resume data because you didn't enable background handling, libtorrent has to re-check the whole file. When you disable the option to keep it, you delete the files, therefore libtorrent doesn't have to check anything, but you download everything again. That's all there is to it, and one of the reasons why I'll nuke that background handling setting sooner than later...

**Comment by ShlomiD83** [comment]
im not talking about the buffering starting again, just about the speed droping.
ill make a video if it will help..

**Comment by ShlomiD83** [comment]
http://www31.zippyshare.com/v/bH07S1qO/file.html
i used psr.exe, tell me if thats sufficient.

**Comment by scakemyer** [comment]
I appreciate the effort but I can't open that file, and I'm not installing anything to do so either. Please convert it or make a standard video.

**Comment by ShlomiD83** [comment]
its an mht file, it opens in IE, ill try something else.

**Comment by scakemyer** [comment]
Had an old Windows VM lying around, don't bother... it looks like libtorrent is stuck; we don't really control the buffering and all from Quasar other than setting piece priorities, so I'm not sure what would cause this..

**Comment by ShlomiD83** [comment]
it started since 0.9.60 i think, it was fine before that.

**Comment by scakemyer** [comment]
Only thing I can see would be file priorities for season packs from #647, which was in 0.9.57.. mind trying 0.9.56 vs 0.9.57? I could really use logs from both also, or at least from 0.9.65 if the problem wasn't between those two versions.

**Comment by scakemyer** [comment]
Just a hunch but... can you try to set a download and upload bandwidth limit in the settings?

**Comment by ShlomiD83** [comment]
0.9.56 http://paste.ubuntu.com/23924490/ this one worked fine
0.9.57 http://paste.ubuntu.com/23924522/ this one didnt, speed dropped.

**Comment by ShlomiD83** [comment]
0.9.65 with download and upload rates limited http://paste.ubuntu.com/23924670/ didnt work either.

**Comment by scakemyer** [comment]
One last thing you might want to try is enabling the "Limit rates after buffering only", but my hunch about integer overflows in libtorrent doesn't seem to be the problem... But it is something in libttorrent that flags the torrents as "finished" after checking the files the second time you start streaming.

After receiving metatadata, libtorrent goes:
- In 0.9.56: `checking` -> `paused` -> `downloading` -> `checked` -> `resumed`
- In 0.9.57: `checking` -> `downloading` -> `checked` -> **`finished`** -> `downloading`

So far it doesn't look like the file priorities fix added in 0.9.57 is the culprit. Bottom line is that I shouldn't have used the tip of libtorrent's RC_1_1, thinking it would be stable enough, and now I have to track down which commit it was using between those versions, and which commit in libtorrent introduced this issue...

**Comment by scakemyer** [comment]
Should be fixed in v0.9.66

**Comment by ShlomiD83** [comment]
just tested it, and the problem is still there.

**Comment by scakemyer** [comment]
That last commit should hopefully fix it in 0.9.67...

**Comment by nix87** [comment]
Shlomi try same that but only with Rutor and Ruhunt providers and see if there is still problem?

Seems like this is correct about keeping stuck for some period (about minute and a half) wheny you want to stream again same thing but only with public providers. For some reason Rutor and Ruhunt work for me without a problem though there are public providers too. While private providers don't have problem with this. You can repeat choose stream as long as you want it will always hit your maximum download speed in a second.

**Comment by nix87** [comment]
Shlomi try Ruhunt or Rutor providers, see if the problem is there with those?

**Comment by ShlomiD83** [comment]
not solved in 0.9.67 :/

**Comment by scakemyer** [comment]
Sorry but I just triple-checked and it **is** solved; you've got something messed up in your setup. And why you'd want to wait for libtorrent to re-check partially downloaded files each and every time instead of enabling background handling is beyond comprehension. Just enable the damn setting if you like to resume where you left off.

**Comment by ShlomiD83** [comment]
I never had to enable it, quasar always checked existing files. That's changesd. Maybe i should. Have restarted kodi after the update.

**Comment by scakemyer** [comment]
No, this hasn't changed either, it always was this way since background handling was implemented. If it's not enabled, Quasar deletes the .torrent file and resume data, and libtorrent has to re-check partially downloaded files again. I really have to stop talking about removing the background handling setting and just do so...

**Comment by ShlomiD83** [comment]
Ok, ill check again after work, maybe i missed something.

**Comment by ShlomiD83** [comment]
dont know what to tell you, its still not working over here and in other ppl setups.
the only thing i can think of is maybe issue #643?

**Comment by nix87** [comment]
Really don't know what's not working? You mean when you have some file already on your hdd and you want same that file to play Quasar doesn't recognize existing file? If that you wnna say?

For me when it is situation like this Quasar informs me that I already have same file at my HDD and plays it immediately.

**Comment by scakemyer** [comment]
And I don't know what to tell you either, "it doesn't work" doesn't cut it at this point, or at any point for that matter. I'll need a another description of what you're doing, just in case it's different from what you described previously, the exact settings you're using, a screencast, and matching logs to even consider spending more time on this, because in all my tests in 0.9.67, everything worked just fine no matter the combination of settings I tried.

**Comment by ShlomiD83** [comment]
select the same torrent twice, while having the setting to keep files on, how can i say it in a different way? you need logs again? ill provide them. you want a screen capture video? no problem.
i just want it to work like 0.9.56 worked. nothing changed in my setup for months.

**Comment by scakemyer** [comment]
Yes, and yes. It's called helping us help you. Stating your problem 100 different ways, or saying 100 times it still doesn't work doesn't give us any other important detail or clue as to what might be happening, and neither does saying it worked in this or that version, which equals to asking me to look into thousands of lines of code that changed between those 11 versions, let alone in different projects. I'd like to help you here, and solve this for good for you, but put yourself in my f***ing shoes for one second, and maybe you'll understand why I'm asking for more details.

**Comment by ShlomiD83** [comment]
http://paste.ubuntu.com/23948291/ fresh logs.

**Comment by ShlomiD83** [comment]
youtube hasnt finished yet so ive uploaded the avi file to zippyshare, i hope its ok.
http://www40.zippyshare.com/v/SBN0npsO/file.html

**Comment by ShlomiD83** [comment]
http://www40.zippyshare.com/v/SBN0npsO/file.html

**Comment by ShlomiD83** [comment]
pasted the zippyshare link twice already, why it keeps getting deleted?

**Comment by ShlomiD83** [comment]
https://youtu.be/In0u2x-_4OM

**Comment by ShlomiD83** [comment]
youtube links also? how can i post my video?

**Comment by scakemyer** [comment]
I've got 'em, stop panicking and posting them again

**Comment by ShlomiD83** [comment]
so let me know, thought something was wrong here.

**Comment by scakemyer** [comment]
I will. Already noticed the torrent gets paused, and either it gets checked so fast by libtorrent (are you using an NVMe SSD?) that we don't see the Checking part, or there's something else with paths or whatnot, because it shouldn't go through the Buffering part the second time around. I've also tested over here with your exact same settings, and everything's working as it should. So I recognize there's a problem on your end, but I've yet to find what is causing it and how/if it can/should be fixed.

**Comment by ShlomiD83** [comment]
no NVMe SSD.
thats what i tried to say, the buffering shouldnt happen the second time, but speed dropping is more annoying and im not the only one with the problem, ill try to provide logs from other folks.

**Comment by nix87** [comment]
I saw video xD 

Why don't you have background handling when you quit the video and say don't delete torrent?

**Comment by ShlomiD83** [comment]
problem solved with 0.9.68. thank you :)
