### ISSUE TITLE
Navigation error(HTTPError)

### ISSUE THREAD

**Issue by Rikitik** [scakemyer/plugin.video.quasar#678]
Quasar Version 0.9.60 keeps givving an Navigation error after i choose a Video
[https://paste.debian.net/hidden/e9348603/](url)

PS Quasar version 0.9.61 Keeps crashing and restarting

**Comment by scakemyer** [comment]
Need more complete logs from 0.9.61 if you want any help.

**Comment by scakemyer** [comment]
And enable remote control options in Kodi, that's the issue 99% of the time.

**Comment by Rikitik** [comment]
[https://paste.debian.net/hidden/1f1f428d/](url)
0.9.61 link valid 24 hours

**Comment by scakemyer** [comment]
You must have something else blocking the JSON-RPC calls, because that's where the crash occurs. 0.9.62 will just show a critical log message, but you still won't be able to use it unless you solve that problem. Also note that Kodi 15 is reaching EOL and will not be supported once Kodi 17 is released.

**Comment by Rikitik** [comment]
hmm but 0.0.60 did not crash

**Comment by scakemyer** [comment]
See #673, could be something similar. But it's related to the new, more in-depth duplicate checks, however in your logs the stacktrace get cuts short and I can't see where it's coming from exactly. Unlike the other issue however, the crash is in the JSON-RPC call itself, so I'm guessing Kodi's JSON-RPC service hasn't started yet here...
