### ISSUE TITLE
Error 500 & I can't find a single item

### ISSUE THREAD

**Issue by unster** [scakemyer/plugin.video.quasar#679]
Hi,
about 2-3 days ago Quasar started giving HTTP Error 500 & crashing-restarting in loop.

I've tried to watch anything from Trakt list or by searching TV series name - same issue occurred.

Tested [ShlomiD83 tip](https://github.com/scakemyer/plugin.video.quasar/issues/550#issuecomment-260201930) about settings-services-remote control (I have both on ON), but it didn't help. Also tried clearing cache, restarting Kodi - no improvement.

* Version used: v0.9.61
* Environment: Kodi 16.1
* Operating System and version: Android 6
* Device: Nexbox A95X with newest firmware
* Link to Kodi debug log: https://paste.ubuntu.com/23894449/

Again: I have this setup for a while (months) and issue started to appear just few days ago

**Comment by scakemyer** [comment]
Take a look at #673, might not be the exact same problem, but either way it's related, and I'll try to get that fixed for good in the next release.

**Comment by unster** [comment]
Ok, changing scraper for TMDB solved issue, but... on the other hand: 
- does TMDB give same functionality of tracking series? (can't see that option)
- where do I provide account credentials for TMDB?
- why still do I have Trakt option on main window?

**Comment by scakemyer** [comment]
- Yes
- You don't
- What? Browsing Trakt lists in Quasar has nothing to do with which TV content scraper you're using in your own Kodi library....

**Comment by unster** [comment]
Does fix you provided yesterday (?) solves the issue and I may come back to trakt? ;)

**Comment by scakemyer** [comment]
Look, I don't think you understand what the setting does. It merely tells what your **Kodi library** is using as TV content scraper, so that Quasar knows which type of ID to expect to be able to check for duplicates. I tried to clear it up with the name of the setting, but users also have to do a little mental legwork here to understand this; there's no way around this one here, at least not that I can think of currently. So when you go into Video / Files in Kodi, and open the context menu over the folder with your locally stored TV shows (including Quasar's 'Shows' folder), and choose 'Change content', you should have some TV content scraper chosen, typically TVDB, sometimes TMDB, rarely if even possible Trakt (I don't even know of a content scraper using Trakt for Kodi...). That's what Quasar's setting is about; if you have TVDB chosen there, then choose TVDB in Quasar. You're now telling Quasar what type of ID it will see in your Kodi library, and will allow it to detect duplicates. That's it!
