### ISSUE TITLE
Movies and Shows' names not localized

### ISSUE THREAD

**Issue by elgatito** [scakemyer/plugin.video.quasar#713]
Could not find an issue, so making new one.
When Kodi's languages is not English in Quasar menu is localized, Movie and TV Show names are in English, while Episode names localized.

## Expected Behavior

Movies and TV Shows' names should be localized.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Kodi 15/16/17, SPMC, OSMC, OpenELEC):
* Operating System and version (Android 4/5/6, Windows 7/8/10, macOS 10.11, Ubuntu 16.10):
* Link to Kodi debug log:
<!--- See http://kodi.wiki/view/Log_file/Easy or paste to http://paste.ubuntu.com directly

**Comment by scakemyer** [comment]
You'll have to be more specific about which sections and lists are affected for you. Are you sure you don't have the 'Prefer use of original title' setting enabled? Also, lists from Trakt don't have translations, so that could explain what you're seeing too. Since we're now already querying TMDB for images, I suppose we could get translations also, but it's starting to get pretty expensive on initial network requests at this point...

**Comment by elgatito** [comment]
Quasar - Tv Shows - in trend  - Show name (not localized) - season name (not always localized) - episodes (not alaays localized).
Tried to browse different menu items under Tv Shows, some hang with a spinner until I click back. Some open with localized names. 
Using original names turned off, cache creared.

**Comment by scakemyer** [comment]
Trending lists are from Trakt which don't have translations. We switch to TMDB for seasons and episodes afterwards, so that's why those get translated, and if they're not, contributing translations to TMDB is the best solution for everyone.
The spinner hanging should be fixed in v0.9.69, and I'm glad I made cache clearing less aggressive because as I keep repeating, it often causes more problems than it solves doing so.

**Comment by elgatito** [comment]
I see. I will review that more.
Will try to see if it's possible to get list of movies sorted by dvd release date, should be very useful.

**Comment by scakemyer** [comment]
And totally unrelated to this issue, but sure, even if Trakt / Calendars / All Releases is already that.

**Comment by elgatito** [comment]
What services' APIs are used for lists like most popular, top, latest releases and so on?

**Comment by scakemyer** [comment]
It's all TheMovieDB, and Trakt for Trending and other lists under it, but as I said even from Trakt shows, seasons and episodes are from TMDB.

**Comment by elgatito** [comment]
There is a new filter in /discover queries: https://developers.themoviedb.org/3/discover
Called "with_release_type".
Example query: https://api.themoviedb.org/3/discover/movie?api_key=&language=en-US&sort_by=release_date.desc&include_adult=false&include_video=false&page=1&primary_release_date.lte=2017-02-14&release_date.lte=2017-02-14&vote_count.gte=10&with_release_type=4%7C5%7C6

Release dates support different types:
Premiere
Theatrical (limited)
Theatrical
Digital
Physical
TV

So in theory it should be "&with_release_type=4|5|6&sortby=release_date.desc". But I don't like the output, looks shitty.. 

Can't see any good way to get list of released items. Will try to find one later.
