### ISSUE TITLE
Quasar download status window on kodi interface

### ISSUE THREAD

**Issue by KillerJoeBR** [scakemyer/plugin.video.quasar#724]
Since the new version got rid off the "background handling" setting, we get a downloading status whenever we start a new torrent or there is one downloading in the background. This alone can be distracting and uncessary and polutes the kodi interface (we can check the torrents diretory inside Quasar to check all the torrents etc) But i guess it's useful for others. 

But the biggest problem is that some skins (at least Emimence) the download progress windows stays over during playback and that's REALLY distracting. 

So i think it's reasonable to ask if you could make an option to disable this status overlay inside the settings. Like i said i think it polutes the interface (and maybe someone doesn't want a window showing kodi is downloading the lastest Bridget Jones or something like that) and besides that some skins keeps the message even while watching the movie.

===>   http://imgur.com/a/lAMJo

Thanks

**Comment by scakemyer** [comment]
I understand the annoyance, but it's those skins that need be fixed and have an option to disable their **background** dialogs while watching something. Minor nitpick but don't confuse overlay status with download progress either. Really sorry about this but file an issue with them.

**Comment by KillerJoeBR** [comment]
I didn't know how it was called, sorry. But like i said, i know the skin can correct that (altough the skin that i use is not being updated anymore), but even besided this i think there is merit and have an option to disable this overlay that keeps showing over kodi interface while you are browsing something else. We can check the torrents inside the Quasar addon, going to the torrents section. No need to have a screen showing everywhere. (for me and i guess others. But don't get rid of it, just need an option to disable/hide it)

**Comment by scakemyer** [comment]
Another important point is that download progress is responsible for pausing torrents based on the ratios and seed time you set, so those settings were getting ignored for everyone with background handling disabled. You also have to keep in mind that with or without the setting, downloading has **always** been a background process anyway, and the setting merely exposed that fact and made deleting the torrent and resume data the default, which also caused problems of their own. Anyway... I'll add your f***ing setting since you're the one asking for it...
