### ISSUE TITLE
Providers should return the `size` and `provider` fields to keep streams clean

### ISSUE THREAD

**Issue by scakemyer** [scakemyer/plugin.video.quasar#73]
v0.9.6 introduces a new layout to choose streams, and stream names will be truncated to 80 characters. Please use the `size` field (string) and `provider` instead of concatenating it all in one line.

**Comment by dtsexpert** [comment]
0.9.6 works fine, few minor things I would like to report
1. Exiting the Kodi makes it freeze. Need to hard reboot by unpluging the power cord
2. Love the new list font size and layout, but on top of the feed list there is smaller popup showing 'opening stream'. If I hit cancel it closes the feed list as well. I still can scroll up and down the feed list. Clicking at one of the feed, kodi downloads and plays fine.
Android box 5.1.1, Kodi 14.2

**Comment by scakemyer** [comment]
Thanks for the report but this has nothing to do with this notice of a small API change, please file a different issue regarding those.

**Comment by i96751414** [comment]
@scakemyer I am not aware of your changes, but we could create a new window just for this (skinning). I'm currently doing one window for insert magnet/open torrent file. I can also do one for this. Btw, this week I had a lot of work, so i couldnt contribute to this project, but now i'm free again :p

**Comment by scakemyer** [comment]
I've added a stripped down (and cleaner) version of PyXBMCt to help with new dialog windows, see how it's used in `dialog.py` if it can help :) Glad to have you back, was missing the frequent new features ;)

**Comment by mancuniancol** [comment]
I've been thinking this week about that.  But, I've been little busy.  I think that it will be better and easier for the providers.  I've proposed that long time ago, but it didn't have any echo :(

Technical question: About the size, it will be integer or string?  which units?

{
    "name": string,
    "provider": string,  -> New name for the key??
    "uri": string,
    "info_hash": string,
    "trackers": [string, ...],    -> this one never works, I've tried to implement once and it was a complete disaster
    "size": int, ?? units 
    "seeds": int,
    "peers": int,
    "resolution": int,
    "video_codec": int,
    "audio_codec": int,
    "rip_type": int,
    "scene_rating": int,
    "language": string (ISO 639-1),
}

Inside of the providers, I would like to have the original idea with the search function.  Instead of  pass a string. I would like to pass a dictionary, where the key "query" is included.
Usually, movie_search and show_search calls search. (I don't remember the exact name of the functions :))
That would me help me to send all the information to know where it is a tv show or movie easier.  Right now, I do inserting flags inside of the string.   
I know that it will have some incompatibility with the current providers.  But, I think that it is the moment to do that change, before more people get.

Any case, I could just create a new function that movie_search, tvshows_search and search calls and It won't be traumatic for the users.

I will wait for your comments

**Comment by mancuniancol** [comment]
I have my second thoughts, I think that I will do that inside of the providers, in that way it won't be people having trouble with old version of providers.

**Comment by scakemyer** [comment]
For `size`, it's just a string, like `1.21 GB`, or `1.21 G`, doesn't matter, no strict checking or anything.

For `provider`, it's the long name of the provider itself.

The point is to keep the `name` field to be just the torrent name.

**Comment by mancuniancol** [comment]
Done, I am adding again the seeds and peers.  I don't know if it is used or not.  torrentz and btjunkie updated.  I will work during the week in the rest.

**Comment by scakemyer** [comment]
Seeds and peers pretty much get overridden by data from trackers before anything is shown, so I wouldn't sweat it with those

**Comment by mancuniancol** [comment]
Good to know. Thanks

**Comment by hfmls** [comment]
raelly like the new design! :)

now i was going to ask if possible, the dialog window next to "chose wich torrent to download", the "progress bar" window(that shows download speed, peers seeds etc), is it possible to make it wider? in some cases the current size isn't enough. Or make it adaptable with torrent name size.

**Comment by scakemyer** [comment]
That's not related to the API changes discussed here, can you please open a different issue for it?
