### ISSUE TITLE
Multiple "Quasar has crashed, restating" notification and then "Crashed too many times"

### ISSUE THREAD

**Issue by unster** [scakemyer/plugin.video.quasar#733]
Hi,
well recently Quasar was working great for me, specially with me finally installing Burst (thanks!), but today I turned my AndroidBox on, tried to turn on Quasar, but instead smooth menu I got multiple "Quasar has crashed, restarting" notifications and finally something about "Crashed too many times, aborting" (or sth like this).

I tried to:
- clean Quasar cache - but I couldn't, I started getting "crashed" notifications again,
- turned Kodi on/off several times as suggested on notification - no change,
- cleared box'es cache from recovery - no change

Also, I am not sure if that's connected, since I installed Burst, stuff I watch doesn't get removed from given folder after finishing watching, and when I remove it manually it seems getting back...

    Version used: v0.9.71
    Environment: Kodi 16.1
    Operating System and version: Android 6
    Device: Nexbox A95X with newest firmware
    Link to Kodi debug log: https://paste.ubuntu.com/24001329/

Thanks in advance for any help here!

**Comment by sask3m** [comment]
You need 9.72 now.

**Comment by scakemyer** [comment]
Please search the other issues before posting new ones... #731

**Comment by unster** [comment]
@scakemyer how I could tell this is the same issue? Have you seen content of that bug? What else was posted beside "catchy" title and empty template?

**Comment by elgatito** [comment]
From the log file:

`
NOTICE: [plugin.video.quasar] [33mWARN  main         ▶ ensureSingleInstance  [0mUnable to acquire lock "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/.lockfile": Lockfile created, but doesn't exist, killing...
NOTICE: [plugin.video.quasar] [35mCRIT  main         ▶ ensureSingleInstance  [0mUnable to get other process owner: open /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/.lockfile: no such file or directory
`

**Comment by scakemyer** [comment]
@elgatito Triple backquotes man, triple backquotes... ```

**Comment by scakemyer** [comment]
@unster The other issue's title was pretty much the worse kind of issue title, it wasn't "catchy", and I'll go change it right after I finish this comment. Yours wasn't much better mind you, don't take it badly but describing an issue with the generic notification messages never really helps. For me "0.9.x crashing" === "Quasar has crashed, restarting" in terms of usefulness to debug an issue. Notice my first comment over there about how useless his initial post was...

You do get points for how you filed yours, system specs in a code block is a nice touch, even though I have to select the link to the log to open it. Mixing up another issue in this is a sure way to make me ignore that part though.

Point is, you filed a better issue overall, only it was *after* a new release that fixed the same issue, discussed and debugged at length in another, previously filed issue, which made yours what we call a duplicate. Now please, don't take any of this personal, but I'd rather have spent the last half-hour on new features instead of explaining that to you.

**Comment by unster** [comment]
@scakemyer you are right, well sorry for the fuzz and again - thank you so much for all the effort here, great job!

**Comment by piratefilmco** [comment]
"New lockfile mechanism causing startup crash on Android in v0.9.71 #731" this title helped me ZERO === 0. "Quasar has crashed, restarting" works
