### ISSUE TITLE
Quasar process not closing on Kodi exit on Windows

### ISSUE THREAD

**Issue by elgatito** [scakemyer/plugin.video.quasar#771]
When closiung Kodi on Windows - Kodi process dissapears from the process list, but quasar.exe is still there and it cuts big ammount of RAM and CPU. Not closing then, just staying there until I kill it.

![quasar-process](https://cloud.githubusercontent.com/assets/1247242/23351128/f481b9c8-fcc7-11e6-9b08-efca0b0d09eb.png)

Log: http://paste.ubuntu.com/24076785/
You can see Kodi is closed at 8:32, but then few messages come from quasar, still process is there.

This bug happen pretty often, don't see any logic. As you can see, I just loaded Kodi, did nothing, and closed Kodi. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 

* Environment name and version:

* Operating System and version: Windows 7

* Link to Kodi debug log: http://paste.ubuntu.com/24076785/

**Comment by sask3m** [comment]
Yeah I've seen that happen on my windows 10 sometimes.

**Comment by elgatito** [comment]
@scakemyer, can you add more debug messages to Quasar daemon, so we can know what is it doing? It there good way to debug running go executable?

**Comment by scakemyer** [comment]
I don't think that's going to help since it's mostly managed / overseen by the Python side of the add-on, and even if it did, the answer would be no, not in a normal release. It's even normal for Quasar to keep running on Windows if/when Kodi crashes. One idea would be to have a health checking loop on Windows only, and if the RPC server goes down, close the daemon too.

**Comment by bloombergg** [comment]
I have seen this on 64bit windows 10

**Comment by stephen8263** [comment]
far.exe to geberate par2 files?  if yes, why torrent?
