### ISSUE TITLE
Quasar configured to not ask for keeping downloading; still user is asked for it

### ISSUE THREAD

**Issue by endlessterror** [scakemyer/plugin.video.quasar#773]
In older (older than 3-months that is) Quasar versions it was possible to configure it to delete automatically the downloaded file, upon playback completion. An option has been renamed to "Do not ask to keep downloading", but nevertheless the issue here is that although the button "Keep files after playback/download completion" is disabled, after stopping the movie the file is still seeded to others... 

## Expected Behavior
With  "Keep files after playback/download completion" disabled, the entire file and torrent should be wiped completely.

## Current Behavior
With  "Keep files after playback/download completion" disabled, the entire file and torrent are still available after playback. If "do not ask to keep downloading" is unchecked the file still remains and is seeded to other!

## Steps to Reproduce (for bugs)
1. Download  a movie
2. Movie plays completely then exits to kodi start screen
3. Even though Quasar is configured to delete (if I understand correctly) the file, it keeps serving it OR asks the user to select whether to keep seeding the file.

## Context
What I want is to avoid filling up the SD card of my RPi2 setup. I do not to be asked each time whether to keep the file downloading. It used to work that way on Quasar but now it doesn't.

## Your Environment
LibreELEC 7.0.3 / Kodi 16

* Version used:
Quasar 0.9.74

Not sure if debug log is needed, if it is, please let me know!

**Comment by scakemyer** [comment]
Normal log would do and be needed if there really is an issue, but otherwise, asking the user to keep downloading solves many other issues, from initial buffering timing out, to wanting to stop playback temporarily, to any other problem during playback. Since the default response to "Keep downloading?" is "No", whether you click it explicitly or just exit the dialog, this maintains the previous behavior of deleting the files according to the "Keep files after playback" setting while allowing the user to keep downloading that single torrent they just stopped but still want to keep watching in five minutes.

So far this looks like 3) is leaning towards "you're not understanding this correctly" unless I'm mistaken or there really is a bug, in which case a log is required to go any further, and if don't like the current behavior, you can either stick to your favourite 3 month old version or think about how to best handle this for weeks on end like I did and propose a better behavior, which I'd be more than happy to implement if it solves everything in a better way. Note that I don't want yet another lengthy discussion about it, you either propose something better or you don't; I've already spent way, way too much time thinking about this.

Regarding your SD card filling up, #440 is just about to land, which would help solve that issue for you if you have longer-term storage connected to it.

**Comment by endlessterror** [comment]
Hello, thanks for the fast response.

Asking the user to keep downloading is a welcome option, but not the issue under discussion here:

> Since the default response to "Keep downloading?" is "No", whether you click it explicitly or just exit the dialog, this maintains the previous behavior of deleting the files according to the "Keep files after playback" setting while allowing the user to keep downloading that single torrent they just stopped but still want to keep watching in five minutes.

I opened this bug about files continuing to download, even though I had keep downloading after playback *disabled*, but what I managed to reproduce is that during download/playback and with the option to "ask to keep downloading" *disabled*, a question popped up asking me the exact same thing! FYI, I did not allow the file to finish downloading. I stopped playback before that happened. 

Apart from the fact that I was (incorrectly, according to my current config) asked to allow the file to keep downloading, the file was correctly (as per the settings) deleted. I am attaching both the quasar settings XML file (trakt settings redacted), as well as a "grep quasar kodi.log" output. If you need the entire log, please let me know.

[Desktop.zip](https://github.com/scakemyer/plugin.video.quasar/files/804755/Desktop.zip)

**Comment by endlessterror** [comment]
An update.

while keeping the same configuration as before, I again started the playback/download of a file. This time, I let the file finish download before stopping it. Once more, I was prompted to keep the file downloading or not (even though I should not be asked to). I answered yes and checked that indeed the file was kept seeding. 

Attaching this second log as well, hope it helps. Could this be an issue due to my non-English (Greek) locale?

PS: the build I am running these tests right now are from my LibreELEC 7.0.3, AMD x64 box (hard disk drive installed).


[quasar2.zip](https://github.com/scakemyer/plugin.video.quasar/files/804817/quasar2.zip)

**Comment by scakemyer** [comment]
I appreciate that you're taking enough time to describe the issue as best as you can, but please don't post zip files of logs, at worst just post the files themselves for images/screenshots, but for logs and xml settings, just a link to their paste-binned content on paste.ubuntu.com, ghostbin.com, hastebin.com, etc... It's f**king annoying to have to download a zip file, extract it, delete it, rename the shitty folder name it just created (Desktop.zip? really? you want to overwrite my Desktop on top of this shit?), repeat those 4 steps for the second zip, move those second files, rename them again so I know which issue they belong to when I look at them tomorrow which will probably be missing a lot of important information since you thought it'd be a good idea to "grep quasar", and finally take the time to parse through probably still hundreds of lines of logs for you. So by now I'm done looking at your issue for today, and probably until you explain it even more clearly. And try restarting Kodi when you do change those settings; some of them can't be applied until a restart.

**Comment by endlessterror** [comment]
You're killing me :-)

You're right though. I'll upload the files later on. Regarding the description: I have given is as clear as it could be. Quasar asks to keep downloading the file, even though it shouldn't.

**Comment by scakemyer** [comment]
Don't *upload* the files! Put them on https://ghostbin.com or https://paste.ubuntu.com

You also said "ask to keep downloading" is disabled, when the setting is named "*Do not* ask to keep downloading", so which is it? Then you mention "keep downloading after playback" when there's no such setting, and you're mixing two setting names in one just by saying that. Again, which is it? So no, it's not really as clear as it could be. As a developer, I need precision and attention to detail; a single comma in the wrong place can crash the whole thing. So yeah, maybe I expect too much precision in issues, but having to think for half an hour about what the f**king hell the user is trying to say also takes its toll over time. Do your part.

With the setting unchecked, that's what it does, it asks you if you want to keep downloading. If it's checked, it won't ask, and it'll just *keep downloading*. As far as I can tell, everything works as expected and you've got the whole thing backwards.

**Comment by endlessterror** [comment]
> Don't upload the files! Put them on https://ghostbin.com or **https://paste.ubuntu.com**
That *is* uploading ;-) And yes, that's were I intended to put them next (even though it seems it won't be needed).

Not at home, so I could only re-upload the settings file at https://ghostbin.com/paste/omghp

> You also said "ask to keep downloading" is disabled, when the setting is named "Do not ask to keep downloading", so which is it? Then you mention "keep downloading after playback" when there's no such setting, and you're mixing two setting names in one just by saying that. Again, which is it? 

I'm using Kodi in Greek, hence for the misinterpretation. I'll use the English descriptions from now on. Initially, I opened this bug because even though the following are unchecked (hence "false")...

* Keep files after playback/download stops
* Do not ask to keep downloading
* (one more setting this is in the same settings panel with these 2. Not at home right now, so this is out of my memory, if you could post a screenshot I could tell you which one it was)

... when a torrent finishes I am still asked whether I would like to keep downloading the file. Now, I've also read your description below:

> With the setting unchecked, that's what it does, it asks you if you want to keep downloading. If it's checked, it won't ask, and it'll just keep downloading. As far as I can tell, everything works as expected and you've got the whole thing backwards.

What I do not understand is this: isn't the "keep files after playback/download stops" option short-circuiting the "do not ask to ... d/l'ing" one? IOW, with "keep files after playback/download stops" disabled, no download after playback stop should take place, regardless of the "do not ask to keep downloading" option. Unless the "keep files..." option is for something different.

**Comment by scakemyer** [comment]
It's the other way around. If you keep downloading, whether by choosing yes or having "Do not ask to keep downloading" enabled, you can't do anything but to keep the files *while you download* now do you? So yeah, you've got it all backwards. The only actual issue you might be encountering is when changing settings that might not apply until you restart Kodi, but that's for another time.

**Comment by endlessterror** [comment]
Thanks for the clarification, got it now. So best thing I could do for now is enable the "Do not ask to keep downloading". 

> and if you don't like the current behavior, you can either stick to your favourite 3 month old version or think about how to best handle this for weeks on end like I did and propose a better behavior, which I'd be more than happy to implement if it solves everything in a better way. 

I presume others made a fuss about it and that is why you've changed the behavior as it is right now. One man's meat is another man's poison of sorts. Since you've already poured some thought into this I don't think I can offer an alternative here. Just wish things were like they were regarding this behaviour.

One question though. When this option was first introduced in some Q version, what was its default value, true or false? I'm asking, because I have installed Kodi for quite a few computer-illiterate fellas on RPi and if the option is false, they'll outrun the available SD card space in no time. No biggie, but I will have to inform them to check the "Do not ask to keep downloading" in the settings. For the record, previously background download was disabled in the options (again for SD free space issues).

**Comment by elgatito** [comment]
There is some inconsistency with delete/keep settings. 
Maybe its better to make one option of what to do with completed streams: keep, ask to delete, delete. That would be much easier to setup and understand.
