### ISSUE TITLE
Quasar keeps crashing. Version 0.9.75

### ISSUE THREAD

**Issue by sjimmie** [scakemyer/plugin.video.quasar#803]
unexpected fault address 0x45205000

This is the error message. I'm running Kodi 17 on Raspberry Pi 2.
I have the Arm7 package.
I will include the kodi.log.

```
19:10:06.214 530.293152 T:1564472240  NOTICE: [plugin.video.quasar] quasard: starting quasard
19:10:06.217 530.296631 T:1604318128  NOTICE: [plugin.video.quasar] quasar: starting jsonrpc service
19:10:06.218 530.297607 T:1564472240  NOTICE: [plugin.video.quasar] Kodi's JSON-RPC service is available, starting up...
19:10:06.221 530.299805 T:1564472240  NOTICE: [plugin.video.quasar] Deleting stale files set([])
19:10:07.166 531.245605 T:1564472240  NOTICE: [plugin.video.quasar] ESC[36mDEBU  main         ▶ main             ESC[0m________
19:10:07.173 531.252136 T:1564472240  NOTICE: [plugin.video.quasar] ESC[36mDEBU  main         ▶ main             ESC[0m\_____  \  __ _______    ___________ _______
19:10:07.175 531.254150 T:1564472240  NOTICE: [plugin.video.quasar] ESC[36mDEBU  main         ▶ main             ESC[0m /  / \  \|  |  \__  \  /  ___/\__  \\_  __ \
19:10:07.181 531.259888 T:1564472240  NOTICE: [plugin.video.quasar] ESC[36mDEBU  main         ▶ main             ESC[0m/   \_/.  \  |  // __ \_\___ \  / __ \|  | \/
19:10:07.182 531.261292 T:1564472240  NOTICE: [plugin.video.quasar] ESC[36mDEBU  main         ▶ main             ESC[0m\_____\ \_/____/(____  /____  >(____  /__|
19:10:07.183 531.262573 T:1564472240  NOTICE: [plugin.video.quasar] ESC[36mDEBU  main         ▶ main             ESC[0m       \__>          \/     \/      \/
19:10:07.185 531.263916 T:1564472240  NOTICE: [plugin.video.quasar] ESC[36mDEBU  main         ▶ main             ESC[0m
19:10:07.186 531.265198 T:1564472240  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             ESC[0mVersion: v0.9.75 Go: go1.8
19:10:07.187 531.266479 T:1564472240  NOTICE: [plugin.video.quasar] INFO  config       ▶ Reload           ESC[0mReloading configuration...
19:10:07.287 531.365845 T:1564472240  NOTICE: [plugin.video.quasar] INFO  config       ▶ Reload           ESC[0mUsing library path: /home/xbian
19:10:07.354 531.433105 T:1564472240  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             ESC[0mAddon: plugin.video.quasar v0.9.75
19:10:07.355 531.434692 T:1564472240  NOTICE: [plugin.video.quasar] INFO  main         ▶ Migrate          ESC[0mPreparing for first run...
19:10:07.357 531.436523 T:1564472240  NOTICE: [plugin.video.quasar] INFO  main         ▶ Migrate          ESC[0mCreating Quasar repository add-on...
19:10:13.223 537.302002 T:1564472240  NOTICE: [plugin.video.quasar] INFO  main         ▶ Migrate          ESC[0mFound enabled Quasar repository add-on
19:10:14.844 538.923279 T:1564472240  NOTICE: [plugin.video.quasar] unexpected fault address 0x45205000
19:10:20.097 544.175903 T:1564472240  NOTICE: [plugin.video.quasar] System information: linux_armv7 4.4.48+
19:10:20.098 544.177307 T:1564472240  NOTICE: [plugin.video.quasar] Kodi build version: 17.0 Git:2017-02-02-17f79d0
19:10:20.099 544.177917 T:1564472240  NOTICE: [plugin.video.quasar] OS type: Linux
19:10:20.099 544.178650 T:1564472240  NOTICE: [plugin.video.quasar] uname: ('Linux', 'xbian', '4.4.48+', '#1 SMP PREEMPT Sun Feb 12 17:57:41 CET 2017', 'armv7l', '')
19:10:25.100 549.179443 T:1564472240  NOTICE: [plugin.video.quasar] quasard: starting quasard
19:10:25.102 549.181213 T:1564472240  NOTICE: [plugin.video.quasar] Kodi's JSON-RPC service is available, starting up...
19:10:25.104 549.183472 T:1564472240  NOTICE: [plugin.video.quasar] Deleting stale files set([])
19:10:25.105 549.184326 T:1564472240 WARNING: [plugin.video.quasar] Existing process found from lockfile, killing...
19:10:25.106 549.185303 T:1564472240   ERROR: [plugin.video.quasar] OSError(3, 'No such process')
```

**Comment by sjimmie** [comment]
http://pastebin.com/SSmWUiWJ

Logfile

**Comment by sjimmie** [comment]
http://pastebin.com/SSmWUiWJ 

Logfile

**Comment by nix87** [comment]
Just install again 0.9.75 and crashing will stop. If you have .zip file just install that and problem should disapear.

**Comment by sjimmie** [comment]
I removed quasar and reinstalled it from the zipfile but it keeps
crashing...
Any other suggestions?
Maybe I have to reboot in between?

--Boris

**Comment by nix87** [comment]
Do you still have this problem?

**Comment by Erudition** [comment]
Yes, I still have this problem. Fresh .75 zip, tried everything.

**Comment by sjimmie** [comment]
Same here! What do you need to debug? More logfiles? What can I do to help?

**Comment by Erudition** [comment]
I'm on the latest kUbuntu, just updated every package. I tried going back to 73, which is where I first had the problem. Seems it affects both versions. 
The problem started (this time) when I got a power outage due to a winter storm today. Quasar tends to misbehave when not shut down properly; this time the daemon keeps crashing. It thought there must be some half-written junk leftover so I tried to clear the cache, Uninstall providers, Uninstall Quasar, clear Kodi cache, wipe Kodi addon update store, reboot again and again.

**Comment by scakemyer** [comment]
Looks like your `library.db` file got corrupted. Try moving (or removing) `.kodi/userdata/addon_data/plugin.video.quasar/library.db` or the whole folder altogether before reinstalling Quasar. Then put your system on a UPS, setup apcupsd so it shutdowns cleanly when you lose power for extended periods of time, and backup your `.kodi` folder regularly. This is not a Quasar issue...

**Comment by Erudition** [comment]
How is it not a Quasar issue? The file is in Quasar's plugin folder. Every other plugin handles power loss just fine, and it's a good thing too because Kodi could crash which would do the same thing.
Not everybody can afford to put a UPS on every computer, let alone a home theater PC. Either way it's not a solution to a bug.

**Comment by sjimmie** [comment]
Hi Scakemyer,

Thanks for the suggestion! I will test this tonight when I get home but it
sounds like a solid solution!
Please ignore Connor's harsh words, your work is very much appreciated.

Connor; 1) This is still a home project, people are investing lots of
private time into it and you can't demand an enterprise level of support,
please be kind.
2) When your computer crashes and your filesystem gets corrupt you need to
do a chkfs. When a database was open during the time of the crash your
database needs to be recovered.
Simple as that. Would you like to build-in some kind of database corruption
check and fix every time Quasar starts? Maybe... but I can imagine those
features have the lowest priority.

--Boris

**Comment by Erudition** [comment]
I didn't mean to sound harsh, I was just perplexed by the notion that this was not a Quasar issue; this case seems prematurely closed. I appreciate the volunteer work as well - I regret if my reaction to the user-blame was any indication to the contrary. I also didn't demand any support at all, let alone enterprise-level - I merely contributed to this bug report, as I had spent many hours on the issue myself. It's a shame to see the blame shifted and the report closed so swiftly. SJimmie, you're probably right that detecting database corruption could be considered a low priority "feature", and if that was the case, this bug would be left open for a future version and that's fine. I'm not sure it's as hard or rare as you make it sound, seeing as every other plugin works just fine, as well as other torrent applications that also work just fine.
There was never any filesystem corruption, even if the one db file was corrupted (it wasn't) the filesystem is just fine. As a matter of fact the whole point of discussing the database is moot because the suggestion is ineffective. Removing the database entirely so it regenerated did not work. Removing the Quasar user data folder entirely did not even work. In fact, I even backed up and removed the Kodi user data folder, ~/.kodi, and launched Kodi, effectively rendering it a fresh install. Then I installed Quasar alone. The plugin immediately and repeatedly wants you to put in a download path, which sometimes pops up even when you're trying to put in the path, undoing it. Anyway, no matter what the daemon triple crashes. Nothing but Quasar installed.
If the suggestion worked for you, we must have different issues, that happened to have the same error message of OSError(3, 'No such process'). Otherwise, I suspect it won't fix it for you either and the database is not the problem.

**Comment by Erudition** [comment]
However, I took another log at the log and I noticed that, in my case at least, the error includes an exception from libtorrent. So if the torrent library is causing the problem, perhaps it's the torrent files that trigger it? Sure enough, I deleted Quasar's temporary torrent storage folder, in the folder I set my download path to. The daemon stopped crashing! 

Must be that one of the .torrent files was corrupted, makes sense. What's weird though is that I had already tried setting different download paths, including empty ones with no files at all. But I would usually start with the existing path, so I suppose that permanently crashes libtorrent and Quasar no matter how many times you change the path after. Go figure. 

I found a torrent file that when opening in KTorrent, another program, fails to open with a message about corruption - so hopefully this was our problem. If so then another bug report should go under libtorrent for not handling this properly, and this one should focus on making the ambiguous fatal error message helpful. Perhaps something like "daemon crashed due to libtorrent exception, restarting..."

Cheers!

**Comment by sjimmie** [comment]
Hi Connor,

Great! Thanks for the feedback and great that you found the issue with the
corrupt Torrent.
I have the plug-in working again too!

However I haven't removed my download path but I just did as Scameyer
suggested.

Uninstalled Quasar, Removed the Plugin Directory, Rebooted, Installed
Quasar.

Thanks for sharing your solution!
