### ISSUE TITLE
New version still not marking episodes watched status

### ISSUE THREAD

**Issue by KillerJoeBR** [scakemyer/plugin.video.quasar#832]
It shows an error message (bad status...) while starting the download, it plays fine but after playing it doesn't get marked as watched.

LOG:
http://paste.ubuntu.com/24371889/

**Comment by KillerJoeBR** [comment]
The same thing happens even while watching an episode inside Quasar (without using library integration)

**Comment by scakemyer** [comment]
I'm aware of the bad status error, will release a hotfix asap.

**Comment by scakemyer** [comment]
There are lots of `No external IDs found` and playing an episode throws a `No episode found with ID: 0` in your logs. Just to be sure, which TV Show scraper are you using in your library, and does your Quasar setting for it match? (I have the feeling you've got all that set up properly...)

**Comment by elgatito** [comment]
Watched gets updated for some not-so-new episodes?
There are error like these in the log:
```
No external IDs found for S08E19 (1421)
```

We try to find tvdb id from tmdb entry (because your scraper is tvdb for tv shows), so we use tvdb id provided by tmdb.

And if you look at tmdb for this episode - https://www.themoviedb.org/tv/1421-modern-family/season/8/episode/19/changes , you will see tvdb is not filled. You can try to set episode 13 to unwatch, open it, seek to the end and see if it changes to watched. It's the episode with tvdb  id.

**Comment by scakemyer** [comment]
Should all be fixed in v0.9.78
